x-govuk/govuk-form-builder

.rubocop.yml
.travis.yml
README.md
lib/govuk_design_system_formbuilder/base.rb
lib/govuk_design_system_formbuilder/containers/fieldset.rb
lib/govuk_design_system_formbuilder/elements/date.rb
lib/govuk_design_system_formbuilder/elements/hint.rb
lib/govuk_design_system_formbuilder/elements/input.rb
lib/govuk_design_system_formbuilder/elements/label.rb

Added first attempt at .travis.yml

---

lib/govuk_design_system_formbuilder/elements/radios/collection.rb
lib/govuk_design_system_formbuilder/elements/radios/collection_radio_button.rb
lib/govuk_design_system_formbuilder/elements/text_area.rb

Some tidying to boost the CodeClimate score 😒

Fixing minor code smells

---

README.md
govuk_design_system_formbuilder.gemspec
guide/content/css/govuk-design-system-formbuilder-guide.sass
guide/content/form-elements/checkboxes.slim
guide/content/form-elements/select.slim
guide/content/form-elements/text-field.slim
guide/content/index.slim
guide/content/introduction/error-handling.slim
guide/content/introduction/getting-started.slim
guide/content/introduction/labels-hints-and-legends.slim
guide/layouts/partials/example-fig.slim
guide/lib/examples/checkboxes.rb
guide/lib/examples/injecting_content.rb
guide/lib/examples/text_area.rb
guide/lib/examples/text_input.rb
guide/lib/helpers/person.rb

There were several _minor_ mistakes in the guide - mostly spelling mistakes, typos and poor grammar. This should tidy most of them up!

Guide improvements

---

guide/content/form-elements/file-field.slim
guide/content/index.slim
guide/lib/examples/file.rb
guide/lib/helpers.rb
guide/lib/helpers/person.rb
guide/lib/helpers/related_info.rb

Add guide page for the file upload component

Add documentation for file upload fields

---

.rubocop.yml
govuk_design_system_formbuilder.gemspec
guide/Rules
guide/lib/helpers/link_helpers.rb
guide/lib/helpers/person.rb
guide/lib/helpers/related_info.rb
guide/lib/setup/example_data.rb
lib/govuk_design_system_formbuilder/elements/inputs/base.rb

#58 needed some manual intervention

Upgrading rubocop

---

README.md

Dependabot is now integrated add, add the button to the `README` and tidy it up a bit while we're there

Integrate dependabot 🤖

---

README.md
guide/content/css/govuk-design-system-formbuilder-guide.sass
guide/layouts/partials/example-fig.slim
guide/lib/helpers.rb
guide/lib/helpers/link_helpers.rb

This change adds some informative badges to the readme and makes the figures in the guide directly linkable in a somewhat similar fashion to [AnchorJS](https://github.com/bryanbraun/anchorjs).

More documentation improvements

---

guide/content/css/govuk-design-system-formbuilder-guide.sass
guide/content/form-elements/date-field.slim
guide/lib/examples/date.rb
guide/lib/helpers/person.rb

Make the date field documentation better and provide more realistic examples of usage.

Improve guide info for dates with day omitted

---

.travis.yml
guide/content/introduction/supported-versions.slim
spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb
spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb
spec/govuk_design_system_formbuilder/builder/configuration_spec.rb
spec/govuk_design_system_formbuilder/builder/date_spec.rb
spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb
spec/govuk_design_system_formbuilder/builder/select_spec.rb
spec/govuk_design_system_formbuilder/builder/text_area_spec.rb
spec/support/shared/shared_hint_examples.rb
spec/support/shared/shared_label_examples.rb
spec/support/shared/shared_legend_examples.rb
spec/support/shared/shared_localisation_examples.rb
spec/support/shared/shared_text_field_examples.rb

Bump Ruby and Rails to latest versions
* `2.5.7`
* `2.6.5`
* `2.7.0`
* `5.2.4`
* `6.0.2`

Bump Ruby and Rails versions

---

govuk_design_system_formbuilder.gemspec
guide/lib/helpers.rb
lib/govuk_design_system_formbuilder.rb
spec/spec_helper.rb

Update rubocop and pry, fix some new offences

---

lib/govuk_design_system_formbuilder/containers/character_count.rb
lib/govuk_design_system_formbuilder/containers/check_boxes.rb
lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb
lib/govuk_design_system_formbuilder/containers/fieldset.rb
lib/govuk_design_system_formbuilder/containers/radio_buttons_fieldset.rb
lib/govuk_design_system_formbuilder/containers/radios.rb
lib/govuk_design_system_formbuilder/containers/supplemental.rb
lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb
lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb
lib/govuk_design_system_formbuilder/elements/date.rb
lib/govuk_design_system_formbuilder/elements/hint.rb
lib/govuk_design_system_formbuilder/elements/label.rb
lib/govuk_design_system_formbuilder/elements/radios/collection.rb
lib/govuk_design_system_formbuilder/elements/radios/collection_radio_button.rb
lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb
lib/govuk_design_system_formbuilder/elements/select.rb
lib/govuk_design_system_formbuilder/elements/submit.rb
lib/govuk_design_system_formbuilder/elements/text_area.rb
lib/govuk_design_system_formbuilder/traits/input.rb
lib/govuk_design_system_formbuilder/traits/label.rb

Following on from #145 this is a compilation of small readability improvements and refactorings.

Continue refactoring and simplification

---

README.md
guide/content/introduction/supported-versions.slim
guide/package-lock.json
guide/package.json
lib/govuk_design_system_formbuilder/version.rb

Also bump the gem version to `1.2.6`.

Upgrade to version 3.8.0 of the design system

---

README.md
lib/govuk_design_system_formbuilder/version.rb

Just a few tweaks to the README ready for the V2 release.

Spruce up the readme

---

lib/govuk_design_system_formbuilder/base.rb
lib/govuk_design_system_formbuilder/containers/character_count.rb
lib/govuk_design_system_formbuilder/containers/check_boxes.rb
lib/govuk_design_system_formbuilder/containers/form_group.rb
lib/govuk_design_system_formbuilder/containers/radios.rb
lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb
lib/govuk_design_system_formbuilder/elements/date.rb
lib/govuk_design_system_formbuilder/elements/error_message.rb
lib/govuk_design_system_formbuilder/elements/error_summary.rb
lib/govuk_design_system_formbuilder/elements/null.rb
lib/govuk_design_system_formbuilder/elements/select.rb
lib/govuk_design_system_formbuilder/elements/submit.rb

This is a set of small tweaks and tidyings up that Rubocop suggested - originally explored in #233 which was eventually dropped.

Rubocop suggested improvements

---

lib/govuk_design_system_formbuilder.rb
lib/govuk_design_system_formbuilder/base.rb
lib/govuk_design_system_formbuilder/elements/collection_select.rb
lib/govuk_design_system_formbuilder/elements/date.rb
spec/govuk_design_system_formbuilder/builder/configuration/logging_spec.rb

This should allow people who are aware there might be a problem to not be constantly spammed with warnings 🙊

Add configuration option to control logging

---

.github/workflows/tests.yml
.slim-lint.yml
Makefile
govuk_design_system_formbuilder.gemspec
guide/content/building-blocks/injecting-content.slim
guide/content/form-elements/checkboxes.slim
guide/content/form-elements/date-field.slim
guide/content/form-elements/select.slim
guide/content/form-elements/text-field.slim
guide/content/introduction/labels-captions-hints-and-legends.slim
guide/layouts/partials/breadcrumbs.slim
guide/layouts/partials/example-fig.slim

Add the [slim_lint](https://github.com/sds/slim-lint) gem to the app and configure it so it runs within CI.

Enable slim_lint

---

guide/content/css/guide.sass
guide/content/introduction/labels-captions-hints-and-legends.slim
guide/lib/examples/labels_captions_hints_and_legends.rb
guide/lib/helpers/person.rb

It had fallen embarrassingly behind 🤦
Also add a example of setting hint contents using a proc.

Bring the hint text guidance up to date

---

.github/workflows/semgrep-analysis.yml

> [Semgrep](https://semgrep.dev/) is a fast, open-source, static analysis tool for finding bugs and enforcing code standards at editor, commit, or CI time. Its rules look like the code you’re searching; no more traversing abstract syntax trees or wrestling with regexes.
We're running it with the default [Ruby ruleset](https://semgrep.dev/p/ruby).

Add a basic semgrep workflow

---

govuk_design_system_formbuilder.gemspec

Upgrade to final 4.0.0 release of rubocop-govuk

---

lib/govuk_design_system_formbuilder/elements/inputs/number.rb
lib/govuk_design_system_formbuilder/elements/inputs/password.rb
lib/govuk_design_system_formbuilder/elements/inputs/phone.rb
lib/govuk_design_system_formbuilder/elements/inputs/text.rb
lib/govuk_design_system_formbuilder/elements/inputs/url.rb

It's not intended for use externally.

Make the input builder_method private

---

README.md

Refs DFE-Digital/govuk-components/issues/186

Add a table of services that use the form builder

---

.github/workflows/tests.yml
README.md
govuk_design_system_formbuilder.gemspec
guide/content/introduction/supported-versions.slim

The supported versions will be:
* 2.7.6
* 3.0.4
* 3.1.2
* 7.0.2
* 6.1.5

Update supported versions to latest Ruby and Rails

---

.github/workflows/publish.yml
.github/workflows/tests.yml
README.md
guide/content/introduction/supported-versions.slim
guide/package-lock.json
guide/package.json

- Update to latest Ruby/Rails minor versions
- Bump GOV.UK Frontend and Sass

Dependency and version updates

---

govuk_design_system_formbuilder.gemspec

Upgrade to html-attributes-utils version 1

---

README.md
guide/content/introduction/supported-versions.slim
guide/package-lock.json
guide/package.json

Upgrade to govuk-frontend 5.6.0
