x-govuk/govuk-form-builder

.gitignore, lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/file.rb, spec/govuk_design_system_formbuilder/builder/file_spec.rb, spec/support/examples.rb
Adds the missing [file upload](https://design-system.service.gov.uk/components/file-upload/) functionality from the Design System, along with associated docs and specs.
=> Add file field helper

lib/govuk_design_system_formbuilder/containers/fieldset.rb, lib/govuk_design_system_formbuilder/elements/label.rb, lib/govuk_design_system_formbuilder/elements/text_area.rb, spec/govuk_design_system_formbuilder/builder/check_boxes_spec.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb, spec/govuk_design_system_formbuilder/builder/file_spec.rb, spec/govuk_design_system_formbuilder/builder/radios_spec.rb, spec/govuk_design_system_formbuilder/builder/select_spec.rb, spec/govuk_design_system_formbuilder/builder/text_area_spec.rb, spec/support/shared/shared_block_examples.rb, spec/support/shared/shared_error_examples.rb, spec/support/shared/shared_hint_examples.rb, spec/support/shared/shared_label_examples.rb, spec/support/shared/shared_legend_examples.rb, spec/support/shared/shared_text_field_examples.rb
There was a fair amount of duplication across the various specs for methods that take common arguments (`label`, `hint_text`) and have common behaviours (errors and HTML blocks).
Much of this has been moved to `shared_example` blocks and the organisation and readability of the output has been significantly improved.
=> Refactor and de-duplicate specs

lib/govuk_design_system_formbuilder/base.rb, lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb, lib/govuk_design_system_formbuilder/containers/fieldset.rb, lib/govuk_design_system_formbuilder/containers/radio_buttons_fieldset.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection_check_box.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/hint.rb, lib/govuk_design_system_formbuilder/elements/date.rb, lib/govuk_design_system_formbuilder/elements/error_message.rb, lib/govuk_design_system_formbuilder/elements/file.rb, lib/govuk_design_system_formbuilder/elements/input.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, lib/govuk_design_system_formbuilder/elements/radios/collection_radio_button.rb, lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb, lib/govuk_design_system_formbuilder/elements/select.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, lib/govuk_design_system_formbuilder/elements/text_area.rb
There was some duplication across the element helpers in creating labels, hints and errors - these have been moved to `Base` where possible. Similarly, the duplicate building of `aria-describedby` code has been removed.
=> More refactoring, tidying and deduplication

lib/govuk_design_system_formbuilder/elements/error_message.rb, lib/govuk_design_system_formbuilder/elements/error_summary.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb, spec/support/examples.rb, spec/support/shared/shared_error_examples.rb
The error summary displayed all field errors grouped on one line.
This commit changes the error summary to only display the first error for a field.
This PR is a draft as we would like to discuss the testing approach.
Before
----
After
To test this feature a model with two errors on one field was needed. 
We added an extra validation to the existing Person class.
We create an invalid person for these tests and then expect to see the correct message in the error summary. 
This feels brittle and we would like to discuss it.
=> Display one error message per field in error summary

README.md, lib/govuk_design_system_formbuilder/containers/check_boxes.rb, lib/govuk_design_system_formbuilder/containers/radios.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, lib/govuk_design_system_formbuilder/elements/text_area.rb, spec/govuk_design_system_formbuilder/builder/check_boxes_spec.rb, spec/govuk_design_system_formbuilder/builder/radios_spec.rb, spec/govuk_design_system_formbuilder/builder/submit_spec.rb, spec/govuk_design_system_formbuilder/builder/text_area_spec.rb
Version 3 of the [GOV.UK Design System](https://design-system.service.gov.uk/) was recently released and it contains several breaking changes, outlined in their [changelog document](https://github.com/alphagov/govuk-frontend/blob/master/CHANGELOG.md).
This PR aims to bring the form builder completely up to date with Version 3.
=> GOV.UK Design System Version 3

lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/label.rb, spec/support/shared/shared_label_examples.rb
Sometimes labels add noise to a form and are unecessary. An example of
this is when capturing an address with multiple lines. The initial label
'Address' should make it obvious what lines 2-4 are for. The label
should still be present to keep the form accessible.
This change adds the ability to wrap the contents of a label in a span
that hides it visually. There is an example of this technique used in
the [fieldset section of the Design System documentation](https://design-system.service.gov.uk/components/fieldset/).
=> Allow labels to be optionally hidden

Makefile, guide/content/form-elements/radios.slim, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, lib/govuk_design_system_formbuilder/elements/radios/collection_radio_button.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/submit_spec.rb, spec/support/shared/shared_text_field_examples.rb
Allow radio button collections to set **bold** labels. When the `:hint_method` argument is provided this will always be set to true so there is a visual distinction between the hint and the label.
=> Allow bold radio button labels

.travis.yml, Makefile, govuk_design_system_formbuilder.gemspec, guide/content/introduction/supported-versions.slim, guide/lib/helpers/link_helpers.rb, util/version_formatter.rb
The entirety of Rails isn't a _requirement_ of this gem, only certain parts are needed (#39). This PR slims down those requirements. Additionally, the Ruby version has been bumped.
=> Remove rails dependency and increase Ruby version

guide/content/introduction/error-handling.slim, guide/lib/examples/error_handling.rb, guide/lib/helpers/person.rb, lib/govuk_design_system_formbuilder/elements/select.rb, spec/govuk_design_system_formbuilder/builder/select_spec.rb
It appears that GOV.UK select elements do have an error class - this previously hadn't been made obvious by the Design System docs.
This change adds them and adds an example to the [error handling page in the guide](https://govuk-form-builder.netlify.com/introduction/error-handling/).
See https://github.com/alphagov/govuk-design-system/issues/1049 for context
=> Add error classes to select when attribute invalid

lib/govuk_design_system_formbuilder/elements/check_boxes/collection_check_box.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/label.rb, lib/govuk_design_system_formbuilder/elements/label.rb, lib/govuk_design_system_formbuilder/elements/radios/collection_radio_button.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb
Previously it was affecting all labels in the collection and causing
invalid markup. Now the first label is associated with the first
input and when errors are present on the attribute both id and for are
changed accordingly
=> Make the error link only apply to the first label

lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb, lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb
Similar to #43, this fixes a bug with fieldsets with errors where all
labels were associated with the first input.
=> Make fieldset error link apply to first label

lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb, lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/radio_button_spec.rb, spec/support/html_helper.rb, spec/support/matchers.rb, spec/support/shared/setup_builder.rb
The conditional content, as explained in #48, was inserted in the wrong place causing it to render incorrectly. It has been moved so it's now in the correct position:
=> Fix alignment of conditional content beneath radio buttons and checkboxes

guide/content/introduction/supported-versions.slim, lib/govuk_design_system_formbuilder/version.rb
Upgrade to GOV.UK Design System version `3.3.0` and prep release `0.9.7`
=> GOV.UK design system 3.3.0

lib/govuk_design_system_formbuilder/base.rb, lib/govuk_design_system_formbuilder/containers/character_count.rb, lib/govuk_design_system_formbuilder/containers/check_boxes.rb, lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb, lib/govuk_design_system_formbuilder/containers/fieldset.rb, lib/govuk_design_system_formbuilder/containers/form_group.rb, lib/govuk_design_system_formbuilder/containers/radio_buttons_fieldset.rb, lib/govuk_design_system_formbuilder/containers/radios.rb, lib/govuk_design_system_formbuilder/containers/supplemental.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection_check_box.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/hint.rb, lib/govuk_design_system_formbuilder/elements/date.rb, lib/govuk_design_system_formbuilder/elements/error_message.rb, lib/govuk_design_system_formbuilder/elements/error_summary.rb, lib/govuk_design_system_formbuilder/elements/file.rb, lib/govuk_design_system_formbuilder/elements/hint.rb, lib/govuk_design_system_formbuilder/elements/inputs/base.rb, lib/govuk_design_system_formbuilder/elements/label.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, lib/govuk_design_system_formbuilder/elements/radios/collection_radio_button.rb, lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb, lib/govuk_design_system_formbuilder/elements/select.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, lib/govuk_design_system_formbuilder/elements/text_area.rb
This substantially reduces the amount of noise and duplication throughout the library
=> Delegate common rails tag helpers to @builder

guide/content/form-elements/date-field.slim, guide/lib/examples/date.rb, guide/lib/helpers/person.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/date.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb
[Sometimes non-exact inputs are required](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training/pull/404) for dates that the user might not remember, such as their graduation date or when they started a new job. In this case, don't ask for the day - only the month and year.
I believe that Rails will automatically set the date to the first of the month so this approach _should just work_.
cc @chubberlisk @tvararu 
Fixes #56
=> Allow date input to capture only month and year

guide/lib/examples/checkboxes.rb
The previous example was not wrapped in a fieldset so didn't include the ability to display error messages. Now it's properly constructed wrapped and the `link_errors` parameter is provided so it will correctly link with the `govuk_error_summary`.
=> Improve the single checkbox example

README.md, guide/content/introduction/supported-versions.slim, guide/package-lock.json, guide/package.json, lib/govuk_design_system_formbuilder/version.rb
Now development on form builder has slowed and it implements the design system fully a stable release is due.
Since the 0.9 series there have been several major and dozens of minor improvements and fixes, so many that it no longer feels right to document the 0.7 series as _supported_. 0.7 support will be dropped unless there is a call for it, in which case it can be reviewed and if necessary, revived.
The plan is to wait for [the GOV.UK Design System 3.4.0 to be released](https://github.com/alphagov/govuk-frontend/issues/1632) before bumping and releasing 1.0.0.
In the meantime I'll create a roadmap for 1.1.0 that covers the main missing feature, support for automatically populating the labels, hints and legends via Rails' i18n functionality.
=> Version 1.0.0

lib/govuk_design_system_formbuilder/base.rb, lib/govuk_design_system_formbuilder/elements/text_area.rb, lib/govuk_design_system_formbuilder/version.rb, spec/govuk_design_system_formbuilder/builder/text_area_spec.rb, spec/support/examples.rb
Fix bug where JavaScript counters stopped working. The behaviour had changed slightly since Design System 3.3.0 and it caused them to not work. The fact that the textual description of the limit (_You have 38 words remaining_) **must have** the same `id` as the text area except with a `-info` suffix is confusing and doesn't appear to be particularly well documented. We should probably raise this with the frontend team.
Thanks @dankmitchell  for the heads up - I missed this when checking the upgrade. Perhaps this is an indication that some more tests - perhaps Jasmine - are required 🤔
=> Investigate broken character count behaviour

.rubocop.yml, Makefile, govuk_design_system_formbuilder.gemspec, lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/base.rb, lib/govuk_design_system_formbuilder/containers/supplemental.rb, lib/govuk_design_system_formbuilder/elements/label.rb
The `govuk-lint` gem is now displaying deprecation warnings on every run, it has been replaced by the new `rubocop-govuk` gem.
=> Switch from govuk-lint to rubocop-govuk

guide/content/building-blocks/localisation.slim, guide/layouts/partials/example-fig.slim, guide/layouts/partials/landing-page/links.slim, guide/lib/examples/localisation.rb, guide/lib/helpers.rb, guide/lib/helpers/link_helpers.rb, guide/lib/helpers/person.rb, lib/govuk_design_system_formbuilder/base.rb, lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb, lib/govuk_design_system_formbuilder/containers/fieldset.rb, lib/govuk_design_system_formbuilder/containers/radio_buttons_fieldset.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb, lib/govuk_design_system_formbuilder/elements/date.rb, lib/govuk_design_system_formbuilder/elements/hint.rb, lib/govuk_design_system_formbuilder/elements/label.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb, spec/govuk_design_system_formbuilder/builder/file_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/select_spec.rb, spec/govuk_design_system_formbuilder/builder/text_area_spec.rb, spec/support/locales/sample.en.yaml, spec/support/localisation.rb, spec/support/shared/shared_localisation_examples.rb, spec/support/shared/shared_text_field_examples.rb
Adds support for labels, fieldset legends and hints to be set from the locales file rather than be passed into the builder's helpers manually. When used, the order of precedence is passed-in, then localised and finally (in the case of labels) the default - which is the attribute name.
This should make the usage of the builder more familiar to people migrating from the [MoJ GOV.UK Elements Form Builder](https://github.com/ministryofjustice/govuk_elements_form_builder) and generally work in a more Rails-like fashion generally.
This isn't ready for merging just yet and is planned for version 1.1, there are still a few things to be ironed out in the corresponding ticket #68.
Fixes #68
=> Internationalisation

.travis.yml, guide/content/css/rouge.sass, guide/content/form-elements/radios.slim, guide/layouts/partials/example-fig.slim, guide/lib/examples/radios.rb, guide/lib/helpers/link_helpers.rb, guide/lib/helpers/person.rb, guide/lib/setup/example_data.rb, lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection_check_box.rb, lib/govuk_design_system_formbuilder/elements/radios/collection_radio_button.rb, lib/govuk_design_system_formbuilder/traits/collection_item.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb, spec/spec_helper.rb, spec/support/locales/colours.de.yaml, spec/support/localisation.rb, spec/support/shared/shared_localisation_examples.rb
This change allows procs to be provided to the `#collection_radio_buttons` and `#collection_check_boxes` helpers' `:value_method`, `:text_method` and `hint_method` params. These could be used for simple operations like transforming (eg calling `#upcase`) on the retrieved string. Alternatively, it could be used in the following manner to allow the labels and hints to be fully localised
```ruby
->(item) { I18n.t("colours.#{item.name.downcase}") }
```
Refs #68
=> Providing procs to collection helpers

Makefile, guide/content/css/_colours.sass, guide/content/css/rouge.sass, guide/content/introduction/configuration.slim, guide/layouts/partials/landing-page/links.slim, guide/lib/helpers/link_helpers.rb, lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/base.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/containers/fieldset.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, spec/govuk_design_system_formbuilder/builder/configuration_spec.rb, spec/govuk_design_system_formbuilder/builder/submit_spec.rb, spec/support/shared/setup_radios.rb
Add the ability to configure various default behaviours provided by the form builder.
Config can be set in a Rails initialiser in the normal fashion:
```ruby
GOVUKDesignSystemFormBuilder.configure do |conf|
conf.default_submit_button_text  = 'Apply'              # Continue
conf.default_error_summary_title = 'Uh-oh, spaghettios' # There is a problem
conf.default_legend_tag          = 'h3'                 # h1
conf.default_legend_size         = 'l'                  # m
conf.default_radio_divider_text  = 'how about'          # or
end
```
Fixes #73
=> Allow the form builder's default values to be configured

guide/content/building-blocks/localisation.slim, guide/layouts/partials/example-fig.slim, guide/lib/examples/localisation.rb, guide/lib/helpers/link_helpers.rb, guide/lib/helpers/person.rb, guide/lib/setup/example_data.rb, lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/containers/fieldset.rb, lib/govuk_design_system_formbuilder/elements/hint.rb, lib/govuk_design_system_formbuilder/elements/label.rb, lib/govuk_design_system_formbuilder/traits/localisation.rb, spec/govuk_design_system_formbuilder/builder/configuration_spec.rb, spec/support/locales/custom_contexts.en.yaml, spec/support/locales/custom_fallback.en.yaml, spec/support/locales/sample.en.yaml, spec/support/shared/shared_localisation_examples.rb
Add support for customising the localisation schema (provided in #68) as part of the application config.
The configuration allows for the value `localisation_schema_fallback` to be set, which provides a default 'base' schema; and `localisation_schema_label`, `localisation_schema_hint`, and `localisation_schema_legend` to be set which configures labels, hints and legends respectively.
One slightly-breaking change (from the initial version of localisation functionality) is that now we're referring to fieldset legends by _legend_ rather than _fieldset_. This is more inkeeping with the language used everywhere else in the project and definitely feels cleaner.
Fixes #80
=> Custom i18n schemas

govuk_design_system_formbuilder.gemspec, guide/Rules
Apply [Nanoc's rubypants filter](https://nanoc.ws/doc/reference/filters/#rubypants) throughout the guide. Rubypants, by default, doesn't affect
`pre` or `code` tags so the samples won't be affected.
| Before | After |
| ----- | ---- |
| ![Screenshot from 2019-12-22 18-17-55](https://user-images.githubusercontent.com/128088/71325643-968ba180-24e7-11ea-8d11-8ac03cb539c5.png) | ![Screenshot from 2019-12-22 18-17-34](https://user-images.githubusercontent.com/128088/71325647-9d1a1900-24e7-11ea-9c94-3a9786298672.png) |
=> Add rubypants for smartypants-like quotes in guide

lib/govuk_design_system_formbuilder/base.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/containers/fieldset.rb, lib/govuk_design_system_formbuilder/elements/hint.rb, lib/govuk_design_system_formbuilder/elements/label.rb
Instead only include it where it's required; label, hint and fieldset.
=> Don't include localisation trait in base class

lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb
This is an attempt to fix a problem that was flagged in a usability/accessibility review of https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training. We have a couple of places where we use `govuk_radio_buttons_fieldset` and `govuk_radio_button` with the `hint_text` option. The problem is that the hint `span` elements end up with the same `id` so they can't be linked to the correct radio button for accessibility purposes.
This seems to be because `FieldsetRadioButton` doesn't pass it's `value` to it's child `Elements::Hint`. Fix is simply to pass the value in the constructor.
We found that `govuk_collection_radio_buttons` already does this. It's not applicable in one of the cases for us because we use a divider within the radio button fieldset.
=> Fix duplicate radio button hints

.rubocop.yml, lib/govuk_design_system_formbuilder/base.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb, spec/govuk_design_system_formbuilder/builder/file_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/select_spec.rb, spec/govuk_design_system_formbuilder/builder/text_area_spec.rb, spec/support/examples.rb, spec/support/shared/shared_error_examples.rb, spec/support/shared/shared_plain_ruby_object_examples.rb, spec/support/shared/shared_text_field_examples.rb
Allow the form builder to operate with plain Ruby objects in addition to `ActiveModel` and `ActiveRecord` ones that support `#errors`. This is useful when performing transient operations like searching.
=> Allow plain ruby objects

spec/spec_helper.rb
allows `fdescribe, fcontext, fit` spec running
quicker and less distracting when developing new features/enhancements
=> Enable focused rspec run

README.md, guide/content/introduction/supported-versions.slim, guide/package-lock.json, guide/package.json, lib/govuk_design_system_formbuilder/version.rb
Update the supported version to the [newly-released version 3.5.0](https://github.com/alphagov/govuk-frontend/pull/1706).
It would appear that the form builder is already compliant, including the date inputs using `type='text'` and `inputmode='numeric'`.
=> Update supported version to 3.5.0

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/containers/check_boxes.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb
The Design System allows you to pass in any number of CSS classes, it feels like we should do this as well.
=> Add classes option to checkboxes collection component

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb, lib/govuk_design_system_formbuilder/containers/radio_buttons_fieldset.rb, lib/govuk_design_system_formbuilder/containers/radios.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb
Following on from #96 this change makes the behaviour of `#govuk_collection_radio_buttons`, `#govuk_radio_buttons_fieldset` and `#govuk_check_boxes_fieldset` consistent.
=> Add classes support to radios and checkbox helpers

README.md, guide/content/form-elements/text-field.slim, guide/content/introduction/supported-versions.slim, guide/lib/examples/text_input.rb, guide/lib/helpers/link_helpers.rb, guide/lib/helpers/person.rb, guide/package-lock.json, guide/package.json, lib/govuk_design_system_formbuilder/version.rb
The latest version of the design system doesn't add any new form functionality but _does_ update the guidance on capturing numbers using text fields with `inputmode` and `pattern` attributes.
Fixes #100
=> Upgrade to GOV.UK design system 3.6.0

lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, lib/govuk_design_system_formbuilder/version.rb
Previously error messages for checkbox and radio button collections were being rendered before the supplemental (injected) content, which meant they were potentially being displayed quite a
distance from the elements they referred to (see #102)
This change simply moves them beneath the supplemental content.
=> Move checkbox and radio button error messages next to inputs

lib/govuk_design_system_formbuilder/elements/submit.rb, spec/govuk_design_system_formbuilder/builder/submit_spec.rb
Following discussion on DfE Slack, don't wrap `submit` elements in an unnecessary `govuk-form-group`.
=> Don’t wrap submit buttons in govuk-form-group

lib/govuk_design_system_formbuilder/elements/date.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb
The injected content being rendered immediately above the inputs didn't make sense and it increased the distance between the hint/errors and input elements.
The new order is:
0. fieldset legend
1. injected content
2. hint
3. error (if invalid)
4. date part inputs
Fixes #110
=> Reorder the elements in govuk_date_field

lib/govuk_design_system_formbuilder/elements/file.rb, lib/govuk_design_system_formbuilder/elements/select.rb, lib/govuk_design_system_formbuilder/elements/text_area.rb, lib/govuk_design_system_formbuilder/traits/input.rb
As suggested in #111, standardise the order of labels, legends, supplemental content, hints, errors and form inputs throughout all helpers.
=> Reorder elements of other inputs

lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb
Following on from #112, also adjust hints order for radio buttons and checkboxes.
=> Move the hints belonging to radios/checkboxes up

.rubocop.yml, govuk_design_system_formbuilder.gemspec, guide/lib/helpers/formatters.rb, lib/govuk_design_system_formbuilder/traits/localisation.rb, spec/govuk_design_system_formbuilder/builder/text_area_spec.rb, spec/support/shared/shared_text_field_examples.rb
When Rails is configured with [`config.i18n.fallbacks = true`](https://guides.rubyonrails.org/v6.0.0/configuring.html#configuring-i18n) the behaviour of `I18n.exists?` [is unclear](https://github.com/ruby-i18n/i18n/issues/365). It returns true when passed `nil` because fallbacks are considered.
This could be fixed by [specifying `fallback: false` as a keyword arg to `I18n.exists?`](https://github.com/ruby-i18n/i18n/pull/482) but if we have no key there's no point in proceeding to the check stage.
=> Fix bug where translations missing errors shown

govuk_design_system_formbuilder.gemspec
SimpleCov's output changed with v0.18.0[0] and became incompatible with
CodeClimate. For the time being, pin it to 0.17.1
[0] https://github.com/codeclimate/test-reporter/issues/413
=> Pin SimpleCov to 0.17.1 to fix CC integration

lib/govuk_design_system_formbuilder/traits/input.rb
This occurs immediately after ensuring the width isn't blank, it's harmless but totally unneeded.
=> Remove unnecessary check for nil widths

.rubocop.yml, govuk_design_system_formbuilder.gemspec, guide/content/building-blocks/injecting-content.slim, guide/lib/helpers/link_helpers.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/date.rb
After hearing some user feedback it became apparent that the documentation surrounding [content injection](https://govuk-form-builder.netlify.app/building-blocks/injecting-content/) could be clearer. This change adds an example to the documentation of every helper method that allows content injection and adds some more detail to the associated guide page.
=> Improve injected content documentation

guide/content/introduction/labels-hints-and-legends.slim, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/containers/fieldset.rb, spec/govuk_design_system_formbuilder/builder/fieldset_spec.rb
Allow to pass an optional option to the existing legend options hash, in a similar way to the one in labels, to add an extra class `govuk-visually-hidden` to the legend for those cases where we want to avoid visual repetition.
This is in line with recommendations from the design system:
https://design-system.service.gov.uk/get-started/labels-legends-headings/
However, this option only removes visual duplication and will not help users of screen readers. They will still hear both the page heading and the visually hidden `<label>` or `<legend>`.
To prevent this, set the contents of the `<label>` or `<legend>` as the page heading.
=> Extend legend options to enable visually hidden

guide/content/form-elements/submit.slim, guide/lib/examples/submit.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, spec/govuk_design_system_formbuilder/builder/submit_spec.rb
- Allow a custom class to be passed as a string to the submit element (e.g `= f.govuk_submit 'Create', custom_class: 'custom-govuk-class'`
- Append the custom class to the built element
- Add a basic spec to check the custom class is added
- Add a section to the guide
=> Add custom classes to the submit element

Gemfile, Makefile, govuk_design_system_formbuilder.gemspec, guide/lib/suppress_listen_symlink_errors.rb
Nanoc has supported 'live editing' for a while but it hadn't been added
to the guide because I couldn't work out how to specify groups in the
gemspec (it needs to be in the `nanoc` group).
It turns out that adding it to the Gemfile works fine. The guide can now
be run using the make command `make watch-guide` or changing to the
`guide` directory and running `bundle exec nanoc live`.
This is a cleaner solution than the previous one of running two make
commands; one to serve the app and the other to rebuild on file changes.
=> Add support for nanoc live to ease guide writing

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/containers/fieldset.rb
The legend wasn't being displayed by `Containers::Fieldset` when called directly (rather than via another helper), this was due to some weirdness calling `yield` inside `safe_join` in the context of Rails templates.
It's only apparent in `#govuk_fieldset` because it's the only Container class to have its own helper method. `Container` classes work differently to `Element` ones in that they take their block via the HTML method rather than initialize.
There is already more-robust block handling built into the base class for elements, now the `Fieldset` can be called with either a block passed into the initializer or with one passed into `#html`.
=> Fix block handling bug on #govuk_fieldset

guide/content/css/govuk-design-system-formbuilder-guide.sass, guide/content/form-elements/checkboxes.slim, guide/content/form-elements/radios.slim, guide/layouts/partials/fieldset-warning.slim, guide/lib/examples/checkboxes.rb, guide/lib/examples/radios.rb, lib/govuk_design_system_formbuilder/builder.rb
The docs and guide really didn't make it obvious that `link_errors` is required on the first radio button or check box in a fieldset in order to make the link in the error summary function correctly.
This PR adds a `@note` to the `#govuk_radio_buttons_fieldset` and `#govuk_check_boxes_fieldset` methods and adds a yellow warning box to the relevant sections of the guide. The guide examples now contain the correct markup too.
This has been a problem for a while (see #84) and I'm not sure there's a technical fix; it's beyond the builder's remit to keep track of what's been added and to try to guess where to add the link target.
=> Improve link errors documentation for fieldsets

Makefile
`3006` was the default until #129 removed it and it reverted to `3000`.
=> Switch nanoc port to 3006 to avoid clashes

README.md, guide/content/introduction/supported-versions.slim, guide/package-lock.json, guide/package.json
There weren't any changes to form elements so this appears to be straightforward
https://github.com/alphagov/govuk-frontend/releases/tag/v3.7.0
=> Upgrade to design system 3.7.0

guide/content/form-elements/submit.slim, guide/lib/examples/submit.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, spec/govuk_design_system_formbuilder/builder/submit_spec.rb
Strictly speaking, HTML requires just the `disabled` attribute to be present on the input element, but if it is present with a value it will have the same effect.
- Allow disabled attribute to be passed to the submit element
- Add disabled class to disabled elements
- Update guide
=> Disabled submit buttons

lib/govuk_design_system_formbuilder/base.rb, lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb, lib/govuk_design_system_formbuilder/containers/fieldset.rb, lib/govuk_design_system_formbuilder/containers/radio_buttons_fieldset.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection_check_box.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb, lib/govuk_design_system_formbuilder/elements/date.rb, lib/govuk_design_system_formbuilder/elements/error_message.rb, lib/govuk_design_system_formbuilder/elements/error_summary.rb, lib/govuk_design_system_formbuilder/elements/file.rb, lib/govuk_design_system_formbuilder/elements/hint.rb, lib/govuk_design_system_formbuilder/elements/label.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, lib/govuk_design_system_formbuilder/elements/radios/collection_radio_button.rb, lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb, lib/govuk_design_system_formbuilder/elements/select.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, lib/govuk_design_system_formbuilder/elements/text_area.rb, lib/govuk_design_system_formbuilder/traits/caption.rb, lib/govuk_design_system_formbuilder/traits/input.rb, lib/govuk_design_system_formbuilder/traits/label.rb
This PR is a collection of refactorings and tidyings up.
* Simplify HTML construction by separating the bigger sets of nested blocks with indented hashes/arrays into smaller (saner) methods
* Add `GOVUKDesignSystemFormBuilder::Base#to_s` so we needn't call `#html` on every element we're passing into `#safe_join`
* Improve naming conventions:
* `_args` methods are now `_options` as they return the _options_ used to configure Rails helpers
* `extra_args` methods are now `kwargs` to make it more obvious that surplus keyword args are _converted_ to HTML attributes on the input we're generating
=> Some tidying up, refactoring and minor readability improvements

lib/govuk_design_system_formbuilder/elements/submit.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb, spec/govuk_design_system_formbuilder/builder/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/file_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/radio_button_spec.rb, spec/govuk_design_system_formbuilder/builder/select_spec.rb, spec/govuk_design_system_formbuilder/builder/submit_spec.rb, spec/govuk_design_system_formbuilder/builder/text_area_spec.rb, spec/support/matchers.rb, spec/support/shared/shared_html_formatting_examples.rb, spec/support/shared/shared_text_field_examples.rb
A _minor_ formatting bug was introduced in 5772f91 where a `#compact` was removed from an array which resulted in spaces being appended to the end of a class attribute on the submit button, as detailed in #146 
This PR adds shared examples that ensure no attribute has any leading or trailing spaces. Attributes are found using a regular expression that matches anything between two double quotes preceded by an `=`. This approach was chosen over the XPath method because XPath's matching for the root _and_ any child elements seems clunky. I'm no XPath expert but I can't see a way of matching the root, the child or any descendent without using a `or` like this, which is ugly AF:
```ruby
parsed_subject.xpath('*[@class]|/*[@class]|//*[@class]')
```
this approach would also mean we'd need to …
=> Fix attributes with leading or trailing spaces

guide/content/introduction/configuration.slim, lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/elements/caption.rb, spec/support/matchers.rb, spec/support/shared/shared_caption_examples.rb
This follows the same pattern used for legends.
It is possible to set a default, project-wise, caption size by using the configuration block.
I've maintained the default as `m` (as that was the chosen size before, and also the default for legends) in order to not break any services that might be already using this size.
In our service the default for captions, as these are used in all cases with h1 page headers, will be `xl` and this PR will save us from having to manually specify the size in each page we use captions.
Note: I will be sending a separate PR in a few minutes for a separate issue we encounter with localisation of captions. But wanted to split the work for easier review.
=> Allow to set a default caption size via configuration

guide/lib/examples/localisation.rb, lib/govuk_design_system_formbuilder/elements/label.rb
We run into a problem when using the new [captions capability](https://github.com/DFE-Digital/govuk_design_system_formbuilder/pull/135) of the gem where the localised caption of `govuk_collection_radio_buttons` or `govuk_radio_buttons_fieldset` will leak also to each of their corresponding radio option labels.
I think there is not a use-case to use captions in the labels of individual radio or check box options and couldn't find anything in the design system documentation about this, so I opted for the simplest possible solution, but if in the future there is a use-case for having captions also in these option labels, then I suppose a bit of work is neccessary in the localisation to not inherit that of the fieldset.
I didn't see this happening to check boxes, at least in the scenarios I …
=> Fix caption leaking its localisation to radio options

spec/support/matchers.rb, spec/support/shared/shared_html_formatting_examples.rb
Following on from the new formatting checks added in #147 this spec ensures that attributes are correctly-spaced with a single ' '. This should highlight any failings to call #compact on arrays of `class` or `aria-describedby` values.
=> Ensure no HTML attributes contain double spaces

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/select.rb, spec/govuk_design_system_formbuilder/builder/select_spec.rb, spec/support/shared/setup_examples.rb
The `govuk_collection_select` method, which is a wrapper for Rails' `collection_select`, was missing documentation for the `options` and `html_options` keyword args. They are passed through to the wrapped method directly.
The spec covers example use of pre-selecting an option and ensures attributes are correctly set.
Additionally, there was a bug where the custom classes in `html_options` were being overwritten. This has been fixed by 1499941
Fixes #153
=> Add documentation for collection select options and fix html_options class bug

lib/govuk_design_system_formbuilder/containers/character_count.rb, lib/govuk_design_system_formbuilder/containers/check_boxes.rb, lib/govuk_design_system_formbuilder/containers/fieldset.rb, lib/govuk_design_system_formbuilder/containers/form_group.rb, lib/govuk_design_system_formbuilder/containers/radios.rb, lib/govuk_design_system_formbuilder/containers/supplemental.rb, lib/govuk_design_system_formbuilder/elements/caption.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection_check_box.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb, lib/govuk_design_system_formbuilder/elements/date.rb, lib/govuk_design_system_formbuilder/elements/error_message.rb, lib/govuk_design_system_formbuilder/elements/error_summary.rb, lib/govuk_design_system_formbuilder/elements/file.rb, lib/govuk_design_system_formbuilder/elements/hint.rb, lib/govuk_design_system_formbuilder/elements/inputs/email.rb, lib/govuk_design_system_formbuilder/elements/label.rb, lib/govuk_design_system_formbuilder/elements/legend.rb, lib/govuk_design_system_formbuilder/elements/radios/collection_radio_button.rb, lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb, lib/govuk_design_system_formbuilder/elements/select.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, lib/govuk_design_system_formbuilder/elements/text_area.rb, spec/support/shared/shared_legend_examples.rb
The `Containers::Fieldset` class was over-complicated due to it handling the generation of both the fieldset (simple) _and_ the legend (complex). This change introduces a new `Elements::Legend` class that removes the complexity and provides two clean classes instead of one dirty one.
For the most part, the only methods that should be public are `#html`, `#to_s` and those that originate in `Traits`. This was a small tidying up exercise
Prefixes are only really necessary for methods that are either:
* traits - as they're shared among various elements
* ancillary items - where there might be clashes within a single class
(eg classes vs label_classes)
This change generally improves readability without sacrificing the understanding; `Label.options` is clear than `Label.label_options`
* make …
=> Yet more refactoring

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/containers/check_boxes.rb, lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb, lib/govuk_design_system_formbuilder/containers/form_group.rb, lib/govuk_design_system_formbuilder/containers/radio_buttons_fieldset.rb, lib/govuk_design_system_formbuilder/containers/radios.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb, lib/govuk_design_system_formbuilder/elements/date.rb, lib/govuk_design_system_formbuilder/elements/file.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, lib/govuk_design_system_formbuilder/elements/select.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, lib/govuk_design_system_formbuilder/elements/text_area.rb, lib/govuk_design_system_formbuilder/traits/input.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb, spec/govuk_design_system_formbuilder/builder/file_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/select_spec.rb, spec/govuk_design_system_formbuilder/builder/submit_spec.rb, spec/govuk_design_system_formbuilder/builder/text_area_spec.rb, spec/support/shared/shared_custom_class_examples.rb, spec/support/shared/shared_form_group_examples.rb, spec/support/shared/shared_text_field_examples.rb
Allow extra classes to be set on form groups via a `form_group_classes` keyword arg on all helpers that wrap contents in a `govuk-form-group`.
Also standardise the other helpers that allow custom `classes` so they all take either an array or a string.
Fixes #158
=> Form group custom classes

guide/lib/helpers/link_helpers.rb
Now http://haml.info (correctly) redirects to https://haml.info - this new behaviour was making the guide's external link checks fail
=> Change Haml link from http to https

spec/support/shared/shared_legend_examples.rb
The tests were missing for `s`, `l` and `xl` - reducing the coverage to 99.93% 😖
This change covers those sizes and also ensures that the default is
correctly used when no size is supplied. Back on 100%!
=> Add specs for all supported legend sizes

guide/Rules, guide/lib/helpers/formatters.rb
It defaults to XHTML and this causes a few minor 'oddities' in the output when supplying boolean values to attributes; rather than the value being omitted it's set to an empty string `""`.
In the guide, `aria-hidden` is set to `true` in the following style:
```slim
span.govuk-warning-text__icon aria-hidden=true !
```
Changing the format to HTML results in the following change to the output:
```diff
- <span aria-hidden="" class="govuk-warning-text__icon">
+ <span aria-hidden class="govuk-warning-text__icon">
!
</span>
```
=> Set Slim's template format to HTML

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb, lib/govuk_design_system_formbuilder/containers/form_group.rb, lib/govuk_design_system_formbuilder/containers/radio_buttons_fieldset.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb, lib/govuk_design_system_formbuilder/elements/date.rb, lib/govuk_design_system_formbuilder/elements/file.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, lib/govuk_design_system_formbuilder/elements/select.rb, lib/govuk_design_system_formbuilder/elements/text_area.rb, lib/govuk_design_system_formbuilder/traits/input.rb, spec/support/shared/shared_form_group_examples.rb
Instead of only allowing a form group's classes to be configured, this change replaces the `form_group_classes` argument with `form_group` which takes a hash.
Adding a classes key to the hash will append these extra classes to the required ones (`.govuk-form-group`). Any other key/value pairs will be added as attributes to the form group element.
=> Customise form group attributes

README.md, guide/content/introduction/supported-versions.slim, guide/package-lock.json, guide/package.json
The Design System received a minor bugfix update, change supported versions accordingly
=> Bump GOV.UK Design System support to version 3.8.1

lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/base.rb, lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb, lib/govuk_design_system_formbuilder/containers/radio_buttons_fieldset.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, lib/govuk_design_system_formbuilder/traits/conditional.rb, lib/govuk_design_system_formbuilder/version.rb
This fixes a bug in `govuk_radio_button_fieldset` and `govuk_checkbox_fieldset` where the block content was rendered twice. It was caused by the removal of `capture` in 08fe4ffc05 and not picked up by the test suite, probably due to it not using a templating engine and using Ruby directly.
There's probably a case for more investigation on this and perhaps some tests that do fire up Slim and ensure things are as they seem.
=> Fix duplicating content bug

lib/govuk_design_system_formbuilder/elements/check_boxes/collection_check_box.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb, lib/govuk_design_system_formbuilder/elements/hint.rb, lib/govuk_design_system_formbuilder/elements/radios/collection_radio_button.rb, lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb, lib/govuk_design_system_formbuilder/traits/hint.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/radio_button_spec.rb, spec/support/shared/shared_hint_examples.rb
Since updating the `hint` behaviour in #174, the hint functionality for radio buttons and check boxes had fallen slightly out of sync. This change standardises the behaviour and allows them to be set via procs.
=> Fix hints within fieldsets

lib/govuk_design_system_formbuilder/elements/label.rb, lib/govuk_design_system_formbuilder/elements/legend.rb, lib/govuk_design_system_formbuilder/traits/collection_item.rb
This fixes a bug where the contents of the proc would overwrite the rest of the element.
cc @paulrobertlloyd, @tvararu - the advice I gave on the #177 isn't actually necessary, having delved a bit deeper it seems that the way you were calling it originally is indeed legit!
Unfortunately it's a pain to test in the current manner, hence #179 
Either approach will work once this is merged and released.
=> Always capture the output when calling procs

govuk_design_system_formbuilder.gemspec
CodeClimate isn't compatible with SimpleCov 0.18.x, I mistakenly allowed Dependabot to upgrade it in #136 (8b77598b) and it's not been reporting since 🤦
For more info see https://github.com/codeclimate/test-reporter/issues/418
=> Downgrade simplecov to 0.17.1 to fix CodeClimate

lib/govuk_design_system_formbuilder/elements/label.rb, lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/radio_button_spec.rb
Some of the instance variables set in Label's initializer are required for both proc and hash style labels. When set using a proc they are missed and it causes the ids and radio/checkbox-specific classes not to be set properly.
They have now been moved out, only the variables used to configure the appearance of the label are now set in the else clause.
=> Move instance variable assigns out of else block

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/hint.rb, lib/govuk_design_system_formbuilder/elements/legend.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb, spec/support/shared/shared_caption_examples.rb, spec/support/shared/shared_legend_examples.rb
To make the behaviour of fieldset legends more consistent with labels, they will now be added to the form by default if nothing is specified.
This is intended to act as a prompt for the developer to modify the content, so no additional formatting (ie removing underscores) is undertaken.
If the developer wants the legend to be omitted they can pass `nil` to in legend param.
Fieldsets with no attribute name (ie standalone fieldsets called via `govuk_fieldset`) will remain unaffected.
=> Set legend text by default

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/containers/form_group.rb, lib/govuk_design_system_formbuilder/elements/caption.rb, lib/govuk_design_system_formbuilder/elements/file.rb, lib/govuk_design_system_formbuilder/elements/label.rb, lib/govuk_design_system_formbuilder/elements/legend.rb, lib/govuk_design_system_formbuilder/traits/caption.rb, spec/support/shared/shared_caption_examples.rb, spec/support/shared/shared_hint_examples.rb, spec/support/shared/shared_label_examples.rb
This sets any key/value pairs in the `label`, `legend` or `caption` hash that aren't recognised as keyword args as HTML attributes on the relevant element. This makes their behaviour consistent with hints.
=> Allow custom HTML attributes to be set on labels captions and legends

guide/content/css/guide.sass, guide/layouts/partials/example-fig.slim, guide/lib/helpers.rb, guide/lib/helpers/formatters.rb
This was brought up in #177 by @paulrobertlloyd where it was mentioned that [Slim](http://slim-lang.com/) templates might not make sense to people who are more used to [ERB](https://ruby-doc.org/stdlib-2.7.1/libdoc/erb/rdoc/ERB.html). In other documentation often multiple languages/syntaxes are listed, this is a quick test to see if it's feasible.
This approach, using Slim's built-in `Slim::ERBConverter` _mostly_ works:
| Slim | ERB |
| ---- | ---- |
| ![Screenshot from 2020-08-15 11-22-33](https://user-images.githubusercontent.com/128088/90310491-a9753b00-dee9-11ea-8e82-d3f67523163a.png) | ![Screenshot from 2020-08-15 11-07-50](https://user-images.githubusercontent.com/128088/90310476-7337bb80-dee9-11ea-9752-bceabdf87fc5.png) |
There are a couple of areas that don't:
* **Blocks** - the …
=> Test out the generation of ERB input examples

.rubocop.yml, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/hint.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb, spec/support/examples.rb, spec/support/locales/sample.en.yaml, spec/support/shared/setup_examples.rb, spec/support/shared/shared_localisation_examples.rb
This fixes a bug where @value wasn't being assigned when the hint_method param wasn't passed in, even though @value is required to localise it properly.
Tests have been added to ensure it works as expected; for radio collections both the label and hint can be set via localisation and for check boxes just the hint can.
Thanks @zheileman for reporting and diagnosing :+1:
=> Fix localisation of collection labels/hints

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb
When web forms are submitted, [check boxes in their unchecked state are not submitted](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Value) so Rails' `#check_box` helper, which we wrap in `#govuk_check_box`, should automatically create a hidden field with the unchecked value.
This has not been happening because Rails omits the hidden field when the unchecked value is `false`. The form builder always forced the false value to be false and the hidden field wasn't covered by the test suite. The documentation recommends that [a value of `0` should be used to represent it instead](https://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-check_box).
This fix does two things:
* changes the default unchecked value from `false` to `0`
* allows …
=> Fix bug where checkbox hidden field isn't rendered

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/version.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb
The new default behaviour causes too many changes to the HTML output for a minor release, it's been toggled back and changing it will be investigated in v2.0.0
The ability to override is still present.
=> Change the unchecked default value back to false

lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb
When forms are submitted, if a field has no checked check boxes [it's omitted from the form's payload entirely](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Value). To combat this, Rails adds a hidden field with no value before the check boxes are rendered. This form builder doesn't take that step.
This change makes the form builder add a hidden field within `#govuk_check_boxes_fieldset` and adds a spec to ensure its presence.
This behaviour is already provided by `#govuk_collection_check_boxes` which wraps Rails' functionality more closely.
=> Add missing hidden field needed for check box deselection

guide/content/form-elements/text-field.slim, guide/lib/examples/text_input.rb, guide/lib/helpers/person.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/traits/input.rb, spec/support/shared/shared_text_field_examples.rb
This change adds support for the new prefix and suffix text support in GOV.UK frontend. It allows text to be added before and after text inputs in a grey box to give users more context around the data, for example stating the currency of a expected monetary value.
Fixes #159
=> Add prefix and suffix text support

guide/content/css/guide.sass, guide/content/form-elements/checkboxes.slim, guide/lib/examples/checkboxes.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb
This allows us to suppress the generation of a hidden field by the fieldset helper and allows Rails's `check_box` helper to generate its own, providing `multiple: true` is set on both the fieldset and the check box.
As this is a little unintuitive it has been documented in the guide and API docs
=> Add multiple flag to govuk_collection_check_boxes

guide/content/form-elements/checkboxes.slim, guide/lib/examples/checkboxes.rb
This example was out of date, we no longer need to manually specify the hidden field providing we pass a non-false negative value to the checkbox itself.
=> Use a non-false value to render hidden field

guide/content/introduction/labels-captions-hints-and-legends.slim, guide/lib/examples/labels_captions_hints_and_legends.rb
In this case the proc completely overwrites the legend so the wrapping tag needs to be provided manually.
=> Add missing legend to guide proc example

guide/content/introduction/configuration.slim, guide/content/introduction/labels-captions-hints-and-legends.slim, lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/legend.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/configuration_spec.rb, spec/govuk_design_system_formbuilder/builder/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb, spec/support/shared/shared_legend_examples.rb, spec/support/shared/shared_localisation_examples.rb
As per #201, legends shouldn't contain `<h1>` tags by default.
This change modifies the behaviour of legends so that when `tag: nil` the legend content isn't wrapped in any other tags. To override this behaviour, ie when the heading is also the page title, tag can be set to `tag: 'h1'`. to achieve the old behaviour.
The new value for `default_legend_tag` is `nil`.
This is somewhat related to https://github.com/alphagov/govuk-design-system/issues/1364
```slim
= f.govuk_date_field :date_of_birth,
date_of_birth: true,
legend: { text: 'Enter your date of birth' },
hint: { text: 'For example, 31 3 1980' }
```
```html
<div class="govuk-form-group">
<fieldset class="govuk-fieldset" aria-describedby="person-date-of-birth-hint">
<legend class="govuk-fieldset__legend govuk-fieldset__legend--m"> …
```
=> Remove default header tag from legends

guide/content/introduction/error-handling.slim, guide/lib/examples/error_handling.rb, guide/lib/helpers/person.rb, guide/lib/setup/form_builder_objects.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/error_summary.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb, spec/support/examples.rb
In the case where errors are added to the object's `:base`, linking items in the error summary list to a field is impossible. The GOV.UK Design System guidance states that [such errors should link to the first field](https://design-system.service.gov.uk/components/error-summary#linking-from-the-error-summary-to-each-answer).
This change adds a `link_base_errors_to` argument to the error_summary helper that will override the link when errors on the object base are detected.
There's a [new section on the guide](https://deploy-preview-209--govuk-form-builder.netlify.app/introduction/error-handling/#linking-errors-on-the-base-object-to-specific-fields) covering the behaviour in more detail.
Refs #208
=> Allow base errors to link to supplied fields 

guide/content/building-blocks/localisation.slim, guide/lib/examples/localisation.rb, guide/lib/helpers/person.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb, spec/support/locales/collection_hints.en.yaml, spec/support/shared/shared_localisation_examples.rb
The value was missing from the `hint_options` hash, and the consequence was (because a `nil` value) the fallback to the hint text of the fieldset, when declaring individual checkboxes inside a `govuk_check_boxes_fieldset` (for example if one of the check boxes has to reveal a text area)
The code causing the issue was (it was entering in the second branching due to value being `nil`):
```ruby
def schema_path
if @value.present?
[@object_name, "#{@attribute_name}_options", @value]
else
[@object_name, @attribute_name]
end
end
```
If any of the individual check boxes had a hint text declared in the locales, it will show as expected:
=> Propagate value to hint element in FieldsetCheckBox

lib/govuk_design_system_formbuilder/containers/fieldset.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb, lib/govuk_design_system_formbuilder/elements/hint.rb, lib/govuk_design_system_formbuilder/elements/null.rb, lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb, lib/govuk_design_system_formbuilder/traits/caption.rb, lib/govuk_design_system_formbuilder/traits/fieldset_item.rb, lib/govuk_design_system_formbuilder/traits/hint.rb, lib/govuk_design_system_formbuilder/traits/label.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/radio_button_spec.rb, spec/support/examples.rb, spec/support/locales/sample.en.yaml, spec/support/shared/setup_examples.rb, spec/support/shared/shared_localisation_examples.rb
This addresses a problem where elements are always rendered if there's a matching localisation key, even if `nil` is supplied to the helper.
Introducing a `Elements::Null` class simplifies the logic - an alternative solution was to introduce an `:enabled` flag but as we already have :active it was noisy and confusing.
When the relevant argument (`:caption`, `:hint`, `:label` or `:legend`) is nil a `Elements::Null` is built instead of the usual 'active' element. It will never render any HTML and allows the suppression of elements.
The default argument for captions, hints, labels and legends is always an empty hash, so simply not providing any arguments will allow the localisation mechanism to kick in and populate the element.
Fixes #212
=> Allow suppression of elements by passing in nil

lib/govuk_design_system_formbuilder/containers/fieldset.rb, lib/govuk_design_system_formbuilder/elements/legend.rb, spec/support/shared/shared_legend_examples.rb
This fixes a bug #216 that was caused by an oversight when it came to the arguments passed into the legend - for historical reasons, legends were structured differently to Labels, Hints and Captions so the `kwargs` weren't where I expected them to be :man_facepalming: 
This PR brings them all more-or-less inline which fixes the bug automatically.
=> Ensure keyword args applied as attribtues to legends

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/date.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb
The [latest version of the design system](https://github.com/alphagov/govuk-frontend/releases/tag/v3.10.0), introduces support for date inputs that [allow an 'X' to be used in place of an exact date](https://github.com/alphagov/govuk-frontend/pull/1975).
This change implements that functionality but does so in a more-restrictive way; users won't have free reign over the pattern but
can optionally have 'X' added to it by supplying `wildcards: true` as an argument.
Should this be more flexible? Is it even necessary? These special 'dates' will need to be intercepted before Rails tries to parse them anyway, perhaps this should be left as an exercise for the developer 🤔
=> Add support for wildcards in day and month inputs

guide/content/form-elements/checkboxes.slim
This is a really common use case for checkboxes and it's not immediately obvious that `1` and `0` should be used instead of `true` and `false`. Hopefully the link will make the example easier to find. If not it might be worth separating it out into a separate page.
=> Add hyperlink directly to single checkbox example

README.md, guide/content/introduction/supported-versions.slim, guide/package-lock.json, guide/package.json
No form-related changes here, doesn't warrant a gem version bump.
=> Bump govuk-frontend/supported versions to 3.10.1

.github/workflows/tests.yml, .gitignore, guide/content/introduction/supported-versions.slim, guide/lib/setup/form_builder_objects.rb, spec/spec_helper.rb, spec/support/examples.rb, spec/support/shared/setup_builder.rb, spec/support/shared/shared_error_examples.rb, spec/support/utility.rb
Rails 6.1.0 [introduced a new structure for error messages](https://github.com/rails/rails/pull/32313) that [substantially changed the ways errors are accessed and manipulated](https://code.lulalala.com/2020/0531-1013.html).
The library only retrieves errors via `object.errors.messages` which didn't change, but the specs access the errors hash directly.
As we'll need to support both older (5.2.x) versions of Rails for the foreseeable future, multiple ways of adding and removing messages need to be implemented. This is governed by the utility method `rails_version_later_than_6_1_0?` which checks the regular `RAILS_VERSION` environment variable approach but should default to the latest version.
=> Support Rails 6.1.0

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb
Rails has had this functionality [since version 5](https://github.com/rails/rails/pull/18303) so it makes sense for it to be supported here. This change uses the same keyword, `include_hidden`, as Rails so should feel familiar to users. It's intended to [allow forms to be submitted without any of the radios being selected](https://bigbinary.com/blog/rails-5-add-a-hidden-field-on-collection-radio-buttons).
=> Add include_hidden argument to radios collection

guide/content/introduction/supported-versions.slim, guide/package-lock.json, guide/package.json
Bump the supported version of `govuk-frontend` to [3.10.2](https://github.com/alphagov/govuk-frontend/releases/tag/v3.10.2).
=> Bump GOV.UK frontend supported version to 3.10.2

.github/workflows/publish.yml, .github/workflows/tests.yml, spec/spec_helper.rb
This is an attempt to remove some of the manual work required to prep releases and make the output in the actions tab on GitHub a little easier to follow:
=> Improve Github Actions

.github/workflows/tests.yml, govuk_design_system_formbuilder.gemspec
This was a non-trivial upgrade because versions 0.18 and 0.19 of SimpleCov aren't compatible with CodeClimate, but `<= 0.17.1`, and `>= 0.20.0` are.
To make SimpleCov output a 'JSON Coverage report' (in coverage/coverage.json) the `CC_TEST_REPORTER_ID` needs to be present in the RSpec workflow step.
I'm not 100% sure whether it's required for before-build, but added it anyway for good measure.
=> Upgrade to SimpleCov from 0.17.1 to 0.20.0

guide/lib/examples/radios.rb, guide/lib/setup/example_data.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/label.rb, lib/govuk_design_system_formbuilder/traits/collection_item.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb, spec/support/shared/shared_value_examples.rb
There's a bug in the guide where clicking the radio button labels [in the last example](https://govuk-form-builder.netlify.app/form-elements/radios/#populating-values-labels-and-hints-with-procs) doesn't focus the right radio.
It's because the passed-in values are symbols rather than strings.
When a value is passed into the collection helper via a proc as a symbol, it wasn't applied properly when constructing the elements within. This could lead to inputs not having a value, labels not linking to the corresponding input and hints not describing their intended target.
This change ensures that any symbols are converted to strings and adds some tests ensuring that when symbols are supplied via procs the output is rendered properly.
=> Fix radio button procs example in guide

README.md, guide/content/form-elements/submit.slim, guide/content/introduction/supported-versions.slim, guide/lib/examples/submit.rb, guide/package-lock.json, guide/package.json, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/containers/button_group.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, spec/govuk_design_system_formbuilder/builder/submit_spec.rb
The latest revision to the design system brings one change that affects this library, [button groups](https://github.com/alphagov/govuk-frontend/pull/2114).
Previously the behaviour was to automatically apply a right margin to the submit input when additional content was passed into `govuk_submit` via a block.
The new behaviour is to wrap the submit input and the block contents in a `div.govuk-button-group`; this will allow the buttons and links within to be nicely arranged.
=> Upgrade to GOV.UK Frontend version 3.11.0

lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb
The form builder didn't expose any way to set the `#collection_check_boxes` method's `include_hidden` param (which is wrapped by `#govuk_collection_check_boxes`). This was inconsistent with the corresponding radio buttons method `#govuk_collection_radio_buttons` which did.
This PR allows the hidden field to be suppressed by passing `include_hidden: false`.
For consistency, both with each other and with Rails, it changes the default value of the param in the `#govuk_collection_radio_buttons` method to `true`.
As this could affect users so there's also a way of configuring the inclusion of hidden fields on collection fields by setting the options:     `default_collection_check_boxes_include_hidden` and `default_collection_radio_buttons_include_hidden`.
Fixes #238
=> Provide the ability to suppress hidden fields in checkbox collections

guide/content/css/guide.sass, guide/content/form-elements/checkboxes.slim, guide/content/form-elements/date-field.slim, guide/content/form-elements/file-field.slim, guide/content/form-elements/radios.slim, guide/content/form-elements/select.slim, guide/content/form-elements/submit.slim, guide/content/form-elements/text-area.slim, guide/content/form-elements/text-field.slim, guide/lib/helpers/link_helpers.rb
~~The quote in the 'small checkboxes' section should really have been in the 'generating a single checkbox' one. Also tried to improve the phrasing of the single checkbox documentation a little.~~
Ended up rewording most of the guidance on the checkboxes page. It definitely feels like it makes more sense now.
Fixes #243
=> Remove incorrect quote and reword the single checkbox instructions

guide/lib/examples/radios.rb
This alters: https://govuk-form-builder.netlify.app/form-elements/radios/#radio-buttons-fieldset-with-conditional-content-and-a-divider
When adding a text-divider, the list of options has to be hard-coded. It was unclear how to add hint-text to the option in a hard-coded way, since the mentions of hint text for radio options on this page were about doing so programmatically. This change adds an example of how to do this.
=> Add example of hard-coding a radio option hint text

.github/workflows/tests.yml, README.md, guide/content/introduction/supported-versions.slim
This upgrade drops support for:
* Rails 5.2.4
* Ruby 2.5.8
The gem will probably run just fine on them for the foreseeable future but they will no longer for part of the testing matrix and won't be officially supported.
------
It appears that `govuk-rubocop` [hasn't caught up yet](https://github.com/alphagov/rubocop-govuk/releases).
```
$ make ruby-lint
bundle exec rubocop lib spec guide/lib util
Error: RuboCop found unknown Ruby version 3.0 in `.ruby-version`.
Supported versions: 2.4, 2.5, 2.6, 2.7, 2.8
make: *** [Makefile:11: ruby-lint] Error 2
```
We'll wait for this for a time but can switch to vanilla Rubocop if it becomes a blocker.
It appears that [Rails 5.2.4 isn't compatible with Ruby 3.0.0](https://github.com/DFE-Digital/govuk_design_system_formbuilder/pull/232/checks?check_run_i …
=> Add Ruby 3.0.0 to supported versions

spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb
This is probably a bit 'belt and braces' but this adds a couple of checks that ensures that when we're using `link_errors: true` the other inputs in the fieldset aren't affected.
=> Add specs that ensure error linking is targetted

.rubocop.yml, govuk_design_system_formbuilder.gemspec, guide/lib/helpers/formatters.rb, lib/govuk_design_system_formbuilder/elements/radios/collection_radio_button.rb, spec/govuk_design_system_formbuilder/builder/file_spec.rb, spec/support/examples.rb
Since adding Ruby 3.0.0 support (#232), rubocop has failed to run for me locally:
```
Error: RuboCop found unknown Ruby version 3.0 in `.ruby-version`.
Supported versions: 2.4, 2.5, 2.6, 2.7, 2.8
```
As v4.0.0 of govuk-rubocop is on its way out (alphagov/rubocop-govuk/issues/129) we may as well take the opportunity to upgrade.
=> Upgrade to GOV.UK Rubocop version 4.0.0

guide/content/form-elements/date-field.slim
I think this has confused a few people in the past. It's not clear _why_ this library opts to use Rails-style [multi-parameter assignment](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/attribute_assignment.rb#L34), which results in date params that look like `date_of_birth(1i)`.
=> Add guide section on permitting date params

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/date.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb
In teaching vacancies we use a form model pattern which means sometimes the form builder renders date inputs where the builder object date attribute doesn't respond to `:day`, `:month`, `:year`. 
Rather than default values being blank, it would be nice to fallback to retrieving the values from the multi-parameter hash. 
Another approach would be for us to initialise date objects in our form models, but I'd rather the form builder supported this!
=> Allow date inputs to set default values for multi-parameter attributes that aren't date objects

govuk_design_system_formbuilder.gemspec, guide/content/form-elements/select.slim, guide/lib/examples/select.rb, guide/lib/helpers.rb, guide/lib/helpers/link_helpers.rb, guide/lib/setup/example_data.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/collection_select.rb, lib/govuk_design_system_formbuilder/elements/select.rb, lib/govuk_design_system_formbuilder/traits/select.rb, spec/govuk_design_system_formbuilder/builder/select_spec.rb, spec/spec_helper.rb, spec/support/shared/setup_examples.rb
Currently users aren't given much flexibility by `#govuk_collection_select`, which wraps Rails' `#collection_select`. This change introduces a `#govuk_select` helper that wraps `#select` and, as a result, offers the following advantages:
* allows the provision of options via any array
* supports Rails' `#options_for_select`
* allows grouped select boxes
* lets users provide their options using a block.
=> Add basic select helper

lib/govuk_design_system_formbuilder/elements/date.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb, spec/support/examples.rb, spec/support/shared/shared_plain_ruby_object_examples.rb
A recent change caused test failures in some projects because 'odd' values were used to set dates. These included a Struct with day, month and year accessors that allows nil values, as found in the Apply For Postgraduate Teacher Training project.
Now we're calling the method directly if the attribute responds to the segment; as this is now _within_ the if statement rather than a chain of ors, if the value is nil, nil will be returned.
There's an additional failure state to capture and inform when objectsthat are un-datelike are provided.
Fixes #259
=> Make date field value setting more lenient

guide/lib/examples/text_input.rb
I don't see a principled reason to skip this custom width in the guide. I am able to add the relevant width class (.govuk-!-width-two-thirds) successfully when I use the width attribute.
=> Add two-thirds custom width option in text-field guide

guide/lib/helpers/person.rb
This hushes a few warning messages.
=> Change over to new error-adding syntax in guide

.semgrepignore
We _need_ to use eval while building the guide as the snippets are shown in both their raw and rendered forms.
.semgrepignore is the same format as .gitignore, as detailed in the docs
https://semgrep.dev/docs/semgrep-ci/
=> Add Semgrep Ignore file

lib/govuk_design_system_formbuilder/traits/html_attributes.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/radio_button_spec.rb, spec/support/shared/shared_html_attribute_examples.rb
On Teaching Vacancies, schools can define a description, which we pre-fill in an `About school` input as part of our `Create a job` journey...
The eagle eyed user will notice some words are missing...
To be precise any repeated words (Case SenSitive) are missing... 😢 
Stop splitting strings for value attributes, so that `deeper_merge` doesn't remove repeated words
- Perhaps we need to rethink how we split and merge custom attributes
=> We shouldn't split value strings, since deeper_merge will remove repeated words

README.md, guide/content/introduction/supported-versions.slim, guide/package-lock.json, guide/package.json
Version 3.12.0 of the GOV.UK Frontend was released yesterday.
https://github.com/alphagov/govuk-frontend/releases/tag/v3.12.0
=> Upgrade to GOV.UK Frontend version 3.12.0

lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb, lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb, lib/govuk_design_system_formbuilder/traits/conditional.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/radio_button_spec.rb
When either no block or an empty block (i.e., one that fails Rails' `#presence` check) is provided in the block passed to a radio button or check box no conditional content shouldn't be rendered and the data-attribute that's used to toggle it should be omitted.
This tweak moves the logic to earlier in the object's initialisation so that both the `@conditional_content` and `@conditional_id` will not be set when the block is blank.
Closes #281, #282
=> Don't render any conditional content when block is empty

lib/govuk_design_system_formbuilder/traits/fieldset_item.rb
This was a bit of a tricky one to trace as it doesn't manifest in plain Ruby (so wasn't caught by the specs and works properly in the guide) but does from ERB.
Essentially, the refactor to remove duplication between fieldset radios and checkboxes (10fd3fb6f7b6894b2), while looking harmless, sets the `block.call` to a variable that's then captured, rather than capturing the `block.call` directly.
=> Fix conditional content rendering bug

.github/workflows/publish.yml, .github/workflows/tests.yml, README.md, guide/content/introduction/supported-versions.slim, lib/govuk_design_system_formbuilder/version.rb
- Bump Rails to latest versions
- Build against the oldest supported Ruby version
- Release version 2.6.0b1
=> Update Rails to latest versions

lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/error_summary.rb, spec/govuk_design_system_formbuilder/builder/configuration/error_summary_configuration_spec.rb, spec/govuk_design_system_formbuilder/builder/configuration/error_summary_error_message_sorting_configuration_spec.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb, spec/support/examples.rb, spec/support/utility.rb
Ordering can be defined in one of two ways:
* passing in an `order` argument, to `#govuk_error_summary`, e.g., `order: %i(name email date_of_birth)`
* configuring an `default_error_summary_error_order_method` method, like this:
```ruby
GOVUKDesignSystemFormBuilder.configure do |conf|
conf.default_error_summary_error_order_method = :error_order
end
```
Then the error order can be defined on a per-model basis like this:
```ruby
def error_order
%i(name email date_of_birth)
end
```
The method approach has the benefit of being automatically applied on any bound form automatically. The argument-based approach takes precedence and  allows for some extra flexibility, but requires a little extra attention and possibly repetition.
Ordered attributes will have their error messages displayed first, …
=> Allow custom sort order for error summaries

guide/content/building-blocks/injecting-content.slim, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/builder_helper.rb, lib/govuk_design_system_formbuilder/elements/error_summary.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb, spec/govuk_design_system_formbuilder/helper/builder_helper_spec.rb
Allowing additional HTML to be passed into an error summary will help authors provide extra context around an error, as well as just listing the messages.
=> Allow extra content to be injected into error summaries

lib/govuk_design_system_formbuilder/elements/error_summary.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb, spec/support/examples.rb
Although it's unlikely to happen, using the number of error messages as the offset when placing unordered errors at the end of the list is the wrong strategy. If there are enough attributes before the ones we care about in the order arg, we can result in:
`total errors + count < ordered error index`
This leads to the ordered and unordered errors being shuffled together.
This is now avoided by creating an adjustment that's the combined total of error messages and custom ordered attributes, and adding the error counter to it.
=> Improve the error sorting index behaviour

spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb, spec/govuk_design_system_formbuilder/builder/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/radio_button_spec.rb, spec/govuk_design_system_formbuilder/builder/select_spec.rb, spec/govuk_design_system_formbuilder/builder/text_area_spec.rb, spec/support/shared/shared_block_examples.rb, spec/support/shared/shared_hint_examples.rb, spec/support/shared/shared_label_examples.rb, spec/support/shared/shared_legend_examples.rb, spec/support/shared/shared_text_field_examples.rb
The `#with_tag` syntax allows for traversing a HTML document without needing to provide blocks and block parameters at every level.
The following two snippets are equivalent:
```
specify "the div contains a p" do
expect(subject).to have_tag("div") do |container|
expect(container).to have_tag("p")
end
end
```
```
specify "the div contains a p" do
expect(subject).to have_tag("div") { with_tag("p") }
end
```
=> Make better use of RSpec HTML matcher's with_tag

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, spec/govuk_design_system_formbuilder/builder/configuration/submit_configuration_spec.rb, spec/govuk_design_system_formbuilder/builder/submit_spec.rb
This addresses [a bug where `<input type="submit">` doesn't initiate a submission when the very top of the element is clicked](https://github.com/alphagov/govuk_elements/issues/545) and is [more in-line with the Design System guidance](https://design-system.service.gov.uk/components/button/#default-buttons).
Additionally, now it's rendering a `<button>` element the text argument can be provided with a block to allow for custom HTML.
=> Change `govuk_submit` from an `input` element to a `button` element

README.md, guide/content/form-elements/checkboxes.slim, guide/content/introduction/supported-versions.slim, guide/lib/examples/checkboxes.rb, guide/lib/helpers/person.rb, guide/package-lock.json, guide/package.json, lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/configuration/check_box_divider_configuration_spec.rb
- Add the `#govuk_check_box_divider` helper
- Add support for [exclusive checkboxes](/alphagov/govuk-frontend/pull/2151) via an `exclusive:` keyword argument
- Bump GOV.UK frontend supported version to [3.13.0](/alphagov/govuk-frontend/pull/2259)
- Add an guide entry for exclusive checkbox options
=> Upgrade to GOV.UK Frontend version 3.13.0

lib/govuk_design_system_formbuilder/base.rb, lib/govuk_design_system_formbuilder/containers/check_boxes.rb, lib/govuk_design_system_formbuilder/containers/fieldset.rb, lib/govuk_design_system_formbuilder/containers/form_group.rb, lib/govuk_design_system_formbuilder/containers/radios.rb, lib/govuk_design_system_formbuilder/elements/collection_select.rb, lib/govuk_design_system_formbuilder/elements/file.rb, lib/govuk_design_system_formbuilder/elements/select.rb, lib/govuk_design_system_formbuilder/elements/text_area.rb, lib/govuk_design_system_formbuilder/traits/input.rb, lib/govuk_design_system_formbuilder/traits/select.rb
The `#described_by` method was poorly-named and its functionality didn't actually have anything specifically to do with setting the `aria-describedby` value - it's just a generic method that combines the provided arguments into a unique array.
It has been renamed to `#combine_references` and it's now used in several other places where arrays of references to elements are combined.
We can finally get rid of this amazing line from an initializer 😅 
```diff
- @described_by    = described_by(described_by)
+ @described_by    = combine_references(described_by)
```
=> Replace `Base#described_by`

lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb, lib/govuk_design_system_formbuilder/containers/radio_buttons_fieldset.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/fieldset_check_box.rb, lib/govuk_design_system_formbuilder/elements/radios/fieldset_radio_button.rb, lib/govuk_design_system_formbuilder/traits/fieldset_item.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb, spec/support/shared/shared_block_examples.rb
Fix multiple captures and their impact on nested field error links
- prevent the overhead of render calls being made multiple times
- fix the side-effect of incrementing nested field-error ids, thereby breaking links between the error summary and the fields
We have a fairly complex nested field structure for a few of our forms
and error linking using this formbuilder was not working, but works against 
this branch.
On investigation I found that partials for the nested fields were being Rendered multiple times.
This did not actually render the fields multiple times, which I still do not understand
why not, but did increment the id of the nested fields.
- **1. Fieldset class plus super class capture the called block**
Digging into the code I found that the `RadioButtonsFieldset` and …
=> Fix multiple captures and their impact on nested field error links

README.md, guide/layouts/partials/phase-banner.slim, guide/lib/helpers/link_helpers.rb
These were broken after renaming the GitHub project.
=> Update some links after the repo name change

README.md, govuk_design_system_formbuilder.gemspec, guide/content/introduction/supported-versions.slim, lib/govuk_design_system_formbuilder/traits/html_attributes.rb
There were some recent security fixes and version bumps across the supported version. They don't appear to be urgent or affect anything remotely close to this libary, so not worth rushing out a release or anything.
=> Change supported versions to latest Ruby releases

README.md
Renaming the repo meant we needed to generate a new CodeClimate project and re-add the `CC_TEST_REPORTER_ID`.
=> Update the CodeClimate badge settings

lib/govuk_design_system_formbuilder/elements/check_boxes/label.rb, lib/govuk_design_system_formbuilder/elements/label.rb, lib/govuk_design_system_formbuilder/elements/legend.rb, spec/support/shared/shared_caption_examples.rb
Finding by presence is a more-descriptive approach than compacting the array and selecting the first remaining item.
It also gives us the opportunity to make the behaviour around label/legend rendering more intuitive when the key:
* is `nil`
* has `nil` text
* has text but it's empty (`""`)
Now, empty strings will fail Rails' `#presence` check and be treated like `nil`. This means that if you pass `#govuk_text_field(label: { text: "" })` the label will fall back to the localised or default value instead of rendering an empty `<label>` element.
=> Simplify the choice of text for legends and labels

guide/content/introduction/error-handling.slim, guide/layouts/partials/example-fig.slim, guide/lib/examples/error_handling.rb, guide/lib/helpers/person.rb, guide/lib/setup/example_data.rb, guide/lib/setup/form_builder_objects.rb, lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/error_summary.rb, lib/govuk_design_system_formbuilder/presenters/error_summary.rb, spec/govuk_design_system_formbuilder/builder/configuration/error_summary_presenter_configuration_spec.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb
The intention of this presenter is that it provides the current basic behaviour but also provides a convenient way for people with specific requirements to inject them.
It currently requires that it's initialized with an error_messages hash but we may yet tweak that so an instance can be passed in and the error messages set on it.
Refs #310
=> Add a default error summary presenter

lib/govuk_design_system_formbuilder/elements/error_summary.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb
Now we're checking that both the custom class and instance implements `#formatted_error_messages` while simplifying the object setup.
=> Improve the setup of error presenters

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb
The previous behaviour was added very early on in the library's development and has remained unchanged since. It attempted to improve the contrast between the labels and hints by, when both are present, making the labels bold.
Unfortunately in doing so, it ignores the user preference when hints are present and non-bold labels are wanted.
This change updates the `bold_labels` argument default from `false` to `nil`. When left `nil`, the old behaviour is maintained, but now when set to either `true`/`false` the selected behaviour will take precedence.
Fixes #315
=> Make radio labels respect the `bold_labels:` setting

lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/elements/error_summary.rb, spec/govuk_design_system_formbuilder/builder/configuration/error_summary_turbo_prefix_configuration_spec.rb, spec/support/matchers.rb
Allow turbolinks data attribute to be customised
Previously this was hardcoded to 'data-turbolinks' but now [Turbo](https://turbo.hotwired.dev/) is gaining traction it makes sense to add support. This approach will also allow other 'pushstate'/pjax tools to be used if necessary.
The new config item `default_error_summary_turbo_prefix` supports being set to either a string or nil.
When it's a string of 'turbo', every link in the error summary will have the attribute `data-turbo="false"`. The default value is 'turbolinks' so the library's behaviour won't change.
When nil no data attribute will be added to the link.
=> Add support for Turbo

lib/govuk_design_system_formbuilder/elements/error_summary.rb, lib/govuk_design_system_formbuilder/presenters/error_summary.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb
Most of the time we want to link to an error that's on the same page (and managed by the form builder itself) but there may be occasions where we need to do something a little more specialised, such as linking to something outside of the form builder or linking to another page entirely.
The format for #formatted_error_messages is an array of arrays that contain two items; the first is the attribute and the second is the corresponding error message.
Here we're implementing a optional third item that when set will form the error's link target. This will allow developers a greater level of customisation while keeping the library generic.
Refs #325
=> Allow error presenters to override link targets

lib/govuk_design_system_formbuilder/elements/date.rb, lib/govuk_design_system_formbuilder/elements/file.rb, lib/govuk_design_system_formbuilder/elements/text_area.rb, lib/govuk_design_system_formbuilder/traits/html_classes.rb
This improvement follows on from a recent [PR on the components lib](/DFE-Digital/govuk-components/pull/264) where [Rails' class_names](https://github.com/rails/rails/pull/37918) was used to improve the building of lists of HTML classes.
Unfortunately it returns a space-separated string instead of an array - and the method it uses to actually build up the classes, `#build_tag_values`, is private, which makes utilsing it a bit of a pain.
Instead here we're implementing a minimal version of it called `#build_classes`. It uses more-or-less the same class-building strategy as `#build_tag_values` but is less flexible in terms of args it accepts.
=> Improve class building using a utility method

guide/content/form-elements/date-field.slim, guide/lib/examples/date.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/date.rb, lib/govuk_design_system_formbuilder/version.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb
This PR adds the ability for users of the govuk_date_field and Date element to
be able to specify a maxlength attribute on each of the inputs. It defaults to
4 chars for the year, 2 chars for the month and 2 chars for the day.
maxlength_enabled (defaulting to false) and pass it to the Elements::Date constructor
We want to be able to control the number of characters the user is able
to input for the day, month and year inputs without hitting our controller
endpoint and having validations kick in.
=> Support the maxlength attribute when building the Date element

lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/elements/error_message.rb, lib/govuk_design_system_formbuilder/elements/error_summary.rb, lib/govuk_design_system_formbuilder/traits/error.rb, spec/govuk_design_system_formbuilder/builder/configuration/trust_error_messages_spec.rb, spec/support/examples.rb
Error messages are not trusted by default - they are not marked as `html_safe`. This is because the user input might be included in the error message.
Including the user's input in the message (e.g., "31 02 2019 is not a valid date") is not a common practice in GOV.UK projects and sometimes teams might want to add extra formatting, like a line break, to an error message to make it easier to read.
To support this, this change introduces a toggle in the config. When true, it will call `#html_safe` on all error messages before they're injected into the output - this will maintain any HTML tags.
The default value is false - no behaviour will change unless the setting is manually enabled.
Fixes #328
=> Allow error message trust to be toggled

guide/lib/helpers/link_helpers.rb, guide/package-lock.json, guide/package.json, lib/govuk_design_system_formbuilder/elements/error_message.rb, lib/govuk_design_system_formbuilder/elements/hint.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/configuration/localisation_configuration_spec.rb, spec/govuk_design_system_formbuilder/builder/configuration/trust_error_messages_spec.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/radio_button_spec.rb, spec/support/shared/shared_error_examples.rb, spec/support/shared/shared_hint_examples.rb, spec/support/shared/shared_localisation_examples.rb
The next major version of this library will add support for the GOV.UK Design System 4.0.0 which introduces some minor breaking changes:
=> GOV.UK Design System 4.0.0

.github/workflows/tests.yml, README.md, guide/content/introduction/supported-versions.slim, guide/lib/helpers/link_helpers.rb
Version 3.0.0 will add support for Rails 7.0.0 which no longer supports Ruby 2.6.0, so it will be dropped.
As some people might not be able to upgrade immediately, the 2.8.0 series will be considered partially supported - bugs and security issues will continue be fixed but no new functionality added.
=> Update supported versions and docs

lib/govuk_design_system_formbuilder/traits/html_classes.rb, spec/support/examples.rb, spec/support/shared/shared_error_examples.rb, spec/support/utility.rb
- Remove legacy class-building method for Ruby 2.6.0
- Remove fallbacks for Rails 6.0.X
=> Remove fallbacks for old versions of Ruby and Rails

lib/govuk_design_system_formbuilder.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb
This should really have been done with v3.0.0 but was overlooked. As we're targetting Rails 7 by default it should work out of the box.
If you've not made the jump to Rails 7, set `config.default_error_summary_turbo_prefix = 'turbolinks'` in [your form builder config initializer](https://www.rubydoc.info/gems/govuk_design_system_formbuilder/GOVUKDesignSystemFormBuilder).
=> Change default turbolinks prefix to turbo

.github/workflows/tests.yml
The recent update to Psych changed the argument format from positional to keyword arguments. Nanoc uses this format so we should follow.
=> Bump Ruby version to stop guide build failing

lib/govuk_design_system_formbuilder/elements/error_summary.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb
The `tabindex` attribute on the Error Summary no longer needs to be set within the HTML, as this is set via javascript, as of govuk-frontend 4.0.1.
See [govuk-frontend 4.0.1 release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v4.0.1).
=> Remove tabindex from Error Summary

guide/Rules, guide/content/index.slim, guide/content/sitemap.erb.xml, guide/lib/helpers.rb, guide/nanoc.yaml
The Nanoc helper makes this really easy, we're using Nanoc's list of items so partials aren't included and we just need to filter to slim files in `xml_sitemap`.
This doesn't set `changefreq` - not sure how important they are. If we add them they needed to be added to each page's frontmatter individually, probably set to `yearly`
=> Add a sitemap to the guide

spec/support/utility.rb
It's not been used since Rails 6 support was dropped and had a negative effect on coverage.
=> Remove #rails_version spec utility method

govuk_design_system_formbuilder.gemspec, lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/traits/html_attributes.rb, lib/govuk_design_system_formbuilder/version.rb
The `deep_merge` gem is incredibly powerful and versatile but isn't the best fit for the specific task of merging HTML attributes while paying attention to some special rules, like the splitting and merging of certain attributes. This is useful in things like `class:`, where a list of values is represented by a space-delimited string.
The new gem, `html-attributes-utils`, was created using the code removed in this commit as a basis. It will benefit from being easier to test standalone and can be reused in the govuk-components library too - and maybe beyond!
Fixes #356
=> Use `html_attributes_utils` gem over `deep_merge`

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/date.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb
Wildcards are [no longer recommended](https://github.com/alphagov/govuk-frontend/pull/2599) by the design system as of [v4.1.0](https://github.com/alphagov/govuk-frontend/releases/tag/v4.1.0)
Fixes #361
=> Remove wildcard and pattern from date object

lib/govuk_design_system_formbuilder/elements/text_area.rb
The `aria-live="polite"` attribute on text areas with a word/character count is [no longer recommended](https://github.com/alphagov/govuk-frontend/pull/2577/) by the design system as of [v4.1.0](https://github.com/alphagov/govuk-frontend/releases/tag/v4.1.0).
=> Drop the aria-live attribute from text area

.semgrepignore, guide/Rules, guide/lib/filters/dart_sass.rb, guide/package-lock.json, guide/package.json
GOV.UK frontend is [dropping support for libsass/ruby-sass later this year](https://github.com/alphagov/govuk-frontend/discussions/2632) so we're making the jump to dart-sass.
The guide uses the built-in functionality of Nanoc which uses
[libsass](https://nanoc.app/doc/guides/using-common-filters/#using-sass). This change won't affect the form builder library itself.
This implementation uses a custom filter for the time being, if a proper one for Nanoc comes along let's switch to that.
=> Switch from libsass to dart-sass

lib/govuk_design_system_formbuilder/elements/date.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb
In https://github.com/DFE-Digital/govuk-formbuilder/pull/57 the date field was modified to support showing an approximate date (without a day field). However, it seems like it's not quite working as expected as Rails ignores the field as there's no HTML `input` element for the day part of the date.
This is demonstrated by https://github.com/DFE-Digital/apply-for-qualified-teacher-status/pull/250/commits/03e6281e25081610aa70a9b22b541dac256b6c4a which required me to manually add hidden input fields for the two approximate date fields representing the day component, and setting the value to "1".
The built-in Rails equivalent date select helper also renders a hidden field for the day component, so it makes sense that we match this behaviour: …
=> Ensure date field without a day works correctly

guide/content/form-elements/radios.slim, lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, spec/govuk_design_system_formbuilder/builder/configuration/radio_auto_embolden_label_spec.rb, spec/support/examples.rb
The original behaviour of the form builder followed the examples in the Design System documentation at the time and emboldened any radio button labels when hints were present.
[These examples were dropped in 2020](https://github.com/alphagov/govuk-design-system/pull/1284) and the guidance changed. In the referenced PR I said I'd look into changing the behaviour in the form builder but never did.
Modifying the default would be a breaking change so we're just adding a new configuration option, `default_collection_radio_buttons_auto_bold_labels`, for the time being. The default will remain `true` for the time being but may change at the next major release.
To disable the automatic emboldening behaviour add this line to your configuration:
```ruby
GOVUKDesignSystemFormBuilder.configure do |c| …
```
=> Add config to prevent automatic boldening of radio button labels in a collection

guide/lib/examples/checkboxes.rb
The exclusive checkbox option example has inconsistent checkbox names `countries` and `languages` which causes the live guide to have incorrect behaviour.
=> Fix exclusive checkbox option example

README.md, guide/content/stylesheets/components/_prose.scss, guide/layouts/partials/links.slim, guide/lib/helpers/formatters.rb, guide/lib/helpers/link_helpers.rb
It's clear that some people land on the guide expecting it to be a _form builder_, rather than a [`FormBuilder`](https://api.rubyonrails.org/v7.0.0/classes/ActionView/Helpers/FormBuilder.html).
Adding a bit of text on the guide's landing page and a paragraph in the README should point people in the right direction.
- Remove the emoji from the readme 😿
- Add links in README to builders that use this lib
- Add an inset paragraph to the guide on other tools
=> Add some links to platforms that use the form builder

guide/content/stylesheets/components/_highlight.scss
Make `pre>code` background transparent so that it doesn't obscure the text on the following line.
| Before | After |
| -------- | ---------|
| ![Screenshot from 2022-10-30 19-09-50](https://user-images.githubusercontent.com/128088/198897154-05683d16-97bb-48e3-a9a3-326fa40d5599.png) | ![Screenshot from 2022-10-30 19-09-58](https://user-images.githubusercontent.com/128088/198897162-c75d52c4-2910-4d59-bf93-a11cd44752cc.png) |
=> Stop code background colour obscuring text

lib/govuk_design_system_formbuilder/elements/caption.rb, lib/govuk_design_system_formbuilder/elements/hint.rb, lib/govuk_design_system_formbuilder/elements/label.rb, lib/govuk_design_system_formbuilder/elements/legend.rb, spec/support/shared/shared_caption_examples.rb, spec/support/shared/shared_hint_examples.rb, spec/support/shared/shared_label_examples.rb, spec/support/shared/shared_legend_examples.rb
Before, custom classes passed in the `label` hash would override any existing classes.
For example:
```erb
<%= form_with model: @model do |f| %>
<%= f.govuk_text_area :details, label: { text: "Some details", class: "special-class" } %>
<% end %>
```
would output:
```html
<!-- form markup --!>
<label for="model-details-field" class="special-class">
Some details
</label>
<!-- form markup --!>
```
Taking into consideration how the rest of the library behaves, this behvaiour was unexpected and meant users would need to explicitly provide default label classes.
This change makes use of the `HTMLAttributes` and `HTMLClasses` traits so that label elements build classes as usual —except any custom classes are appended.
For example:
```erb
<%= form_with model: @model do |f| %>
<%= …
```
=> Append custom custom classes to labels

README.md, guide/content/introduction/supported-versions.slim, guide/package-lock.json, guide/package.json, lib/govuk_design_system_formbuilder/elements/error_summary.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb
GOV.UK Frontend [was released](https://github.com/alphagov/govuk-frontend/releases/tag/v4.4.0) earlier today.
It looks like the vast majority of the changes are in the JavaScript and don't apply to this gem.
The ones that do are in the error summary; the following suggestions have been implemented 7ee5ce140c9f3ddc6.
> * Remove `aria-labelledby="error-summary-title"` and `role="alert"` from the
>   parent element (govuk-error-summary)
> * Add a div wrapper around the contents of govuk-error-summary with the
>   attribute `role="alert"`
> * Remove `id="error-summary-title"` from the error summary h2
>   (`govuk-error-summary__title`)
=> GOV.UK Frontend 4.4.0

lib/govuk_design_system_formbuilder/traits/localisation.rb
This regexp was previously split over several lines with comments explaining what was going on. It was since simplified but the x wasn't removed.
Thanks @misaka for spotting this!
=> Remove unneeded `x` from localisation regexp

guide/lib/examples/text_input.rb
Using the pattern attribute is no longer advised in the design system.
=> Remove `[0-9]*` pattern from numeric text example

README.md, guide/content/introduction/supported-versions.slim, guide/package-lock.json, guide/package.json
[GOV.UK Frontend 4.4.1](https://github.com/alphagov/govuk-frontend/releases/tag/v4.4.1) was releaed earlier today. It will be supported in the upcoming release.
=> Upgrade govuk-frontend to 4.4.1

.github/workflows/publish.yml, .github/workflows/tests.yml, README.md, govuk_design_system_formbuilder.gemspec, guide/content/introduction/supported-versions.slim
Ruby `3.2.0` is scheduled to be released tomorrow.
We aim to support the latest three major versions of Ruby, which will be `3.2.0`, `3.1.3` and `3.0.5`.
Support for Ruby 2.7 will be dropped. Most projects should have already upgraded to newer versions and the process is quite straightforward so this shouldn't be too problematic for users.
=> Upgrade to Ruby `3.2.0` and bump versions to latest minor release

guide/content/form-elements/submit.slim, guide/content/stylesheets/application.scss, guide/lib/examples/submit.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/containers/check_boxes.rb, lib/govuk_design_system_formbuilder/containers/check_boxes_fieldset.rb, lib/govuk_design_system_formbuilder/containers/form_group.rb, lib/govuk_design_system_formbuilder/containers/radio_buttons_fieldset.rb, lib/govuk_design_system_formbuilder/containers/radios.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb, lib/govuk_design_system_formbuilder/elements/radios/collection.rb, lib/govuk_design_system_formbuilder/elements/submit.rb, spec/govuk_design_system_formbuilder/builder/submit_spec.rb, spec/support/shared/shared_custom_class_examples.rb, spec/support/shared/shared_form_group_examples.rb
Now we are using [html-attributes-utils](https://github.com/DFE-Digital/html-attributes-utils) we can safely merge the `class` param without worrying about overwriting defaults.
html-attributes-utils [maintains a list of mergeable HTML attributes](https://github.com/DFE-Digital/html-attributes-utils/blob/main/lib/html_attributes_utils.rb#L12) (those that contain an array of space-separated values like `class`, `rel`, etc) so will append/overwrite accordingly.
This means we can completely lose `classes:` and treat `class:` like any other HTML attribute, by passing it through via `**kwargs`.
The opportunity was also taken to tidy up some class-building methods [so they're using `build_classes`](https://github.com/DFE-Digital/govuk-formbuilder/blob/main/lib/govuk_design_system_formbuilder/tra …
=> Remove classes argument throughout

guide/content/form-elements/text-input.slim, guide/lib/examples/text_input.rb, guide/lib/helpers/person.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/traits/input.rb, spec/support/shared/shared_text_field_examples.rb
When true, the `extra_letter_spacing` argument adds the class 'govuk-input--extra-letter-spacing' to the text input element. It is available for all text fields and defaults to false.
This behaviour was added in [GOV.UK Design System version 4.6.0](https://github.com/alphagov/govuk-frontend/pull/2230).
=> Add `extra_letter_spacing` argument to text inputs

guide/content/form-elements/submit.slim, guide/content/stylesheets/application.scss, guide/layouts/partials/example.slim, guide/lib/examples/submit.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/submit.rb
Inverse buttons [were recently added to govuk-frontend](https://github.com/alphagov/govuk-frontend/pull/3556) but haven't yet made it to the GOV.UK Design System. This change adds support for them so we're ready when they land.
- Add support for inverse buttons
- Add an example of inverse buttons to the guide
Fixes #427
=> Add support for inverse buttons

README.md, govuk_design_system_formbuilder.gemspec, guide/lib/helpers/link_helpers.rb
The redirects are causing Nanoc's link checker to fail and preventing changes to the guide being published.
=> Replace links to dfe-digital with x-govuk

README.md, govuk_design_system_formbuilder.gemspec, guide/layouts/partials/head.slim, guide/layouts/partials/header.slim, guide/layouts/partials/masthead.slim
Long: ‘GOV.UK Form Builder for Ruby on Rails’
Short: ‘GOV.UK Form Builder’
Companion PR to https://github.com/x-govuk/govuk-components/pull/432
=> Consistent use of project name

README.md, govuk_design_system_formbuilder.gemspec, guide/lib/helpers/link_helpers.rb
Moving from govuk-formbuilder to govuk-form-builder so it's easier to read and more consistent with other projects
=> Fix links after repo name change

README.md, guide/content/introduction/supported-versions.slim, guide/content/stylesheets/application.scss, guide/package-lock.json, guide/package.json
- Upgrade to GOV.UK frontend 4.7.0
- Remove CSS for inverse buttons
=> GOV.UK Frontend 4.7.0

lib/govuk_design_system_formbuilder/traits/fieldset_item.rb
We have a situation where we want to add additional DOM ids to the `aria-controls` attribute of a govuk form element.
The `x-govuk/html-attributes-utils` is used to merge attributes. It handles merging `aria-controls` but not `data-aria-controls`. It's unclear to me why `data-aria-controls` is used here. It seems like the front end javascript moves the data-aria-controls into aria-controls. Can we just set `aria-controls` directly?
If setting `data-aria-controls` rather than `aria-controls` is important, perhaps we could instead modify `x-govuk/html-attributes-utils` to also merge `%i[data aria controls]`
=> Allow merging data-aria-controls

.gitignore, guide/layouts/partials/footer.slim, guide/layouts/partials/header.slim, guide/package.json
- Switch to using .min.js throughout and copy map
- Switch to new syntax for enabling govuk-frontend
=> Fix GOV.UK frontend JavaScript setup in the guide

guide/content/stylesheets/components/_prose.scss
The `code` selector is adding some padding to the code blocks as well as the inline code, which makes the first line slightly more indented than those that follow. It's only really noticable in some examples (like the error) where there are a few lines.
This change targets the code tags directly in paragraphs, leaving blocks unaffected.
| Before | Closeup | After |
| -------- | ------- | -------- |
| ![Screenshot from 2024-01-03 12-04-28](https://github.com/x-govuk/govuk-form-builder/assets/128088/ebf190d9-90b2-496b-90e4-a7af896a094a)|![image](https://github.com/x-govuk/govuk-form-builder/assets/128088/4f73642c-a162-4b7d-ac06-eeafbe8bd14c) | ![Screenshot from 2024-01-03 12-04-28](https://github.com/x-govuk/govuk-form-builder/assets/128088/94e70a8a-a6cb-47ff-97a3-47a3e9a2a180) |
=> Fix spacing on code examples in the guide

guide/lib/helpers.rb, lib/govuk_design_system_formbuilder/containers/supplemental.rb, spec/support/shared/shared_block_examples.rb
The supplemental conent the form builder allows to be passed in via a block, which is rendered between the hint text and input, isn't very accessible. It encourages the use of longer text than would ordinarily be used in a hint, but screen readers will read out the entire message, which doesn't make for a great user experience.
Refs #445
=> Add warning message for supplemental content

.github/workflows/tests.yml, README.md, guide/content/introduction/supported-versions.slim
This drops support for Ruby 3.0 as it's no longer in the last 3 major releases.
=> Upgrade supported Ruby versions to 3.1, 3.2, 3.3

.rubocop.yml, guide/lib/helpers/header_helper.rb, guide/lib/setup/example_data.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/builder_helper.rb, lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb, lib/govuk_design_system_formbuilder/elements/date.rb, lib/govuk_design_system_formbuilder/traits/localisation.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/check_box_spec.rb, spec/govuk_design_system_formbuilder/builder/check_boxes/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/error_summary_spec.rb, spec/govuk_design_system_formbuilder/builder/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/collection_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/fieldset_spec.rb, spec/govuk_design_system_formbuilder/builder/radios/radio_button_spec.rb, spec/govuk_design_system_formbuilder/builder/select_spec.rb, spec/govuk_design_system_formbuilder/builder/submit_spec.rb, spec/govuk_design_system_formbuilder/builder/text_area_spec.rb, spec/govuk_design_system_formbuilder/helper/builder_helper_spec.rb, spec/support/shared/localisation_examples/setting_the_hint_via_localisation_with_a_proc_examples.rb, spec/support/shared/localisation_examples/setting_the_label_via_localisation_with_a_proc_examples.rb, spec/support/shared/shared_hint_examples.rb, spec/support/shared/shared_label_examples.rb, spec/support/shared/shared_legend_examples.rb, spec/support/shared/shared_text_field_examples.rb
- Set TargetRubyVersion to 3.1
- Run Rubocop with autocorrect
=> Upgrade Rubocop target Ruby version and apply suggested fixes

guide/lib/examples/checkboxes.rb
This makes it a bit clearer how to set the hint text within the legend for checkboxes. Currently it's being set by some text in a localisation file, but this isn’t shown in the example.
Also reworded the examples slightly to make them plural, so that it’s more obvious that uses can select more than one answer.
=> Make it clearer how to set hint text on checkboxes

.github/workflows/codeql.yml, .github/workflows/publish.yml, .github/workflows/tests.yml
This gives us a single job to check the status for before allowing merges and lets us enable the 'merge when all checks pass' feature in GitHub
=> Add permit-merge job to workflow

guide/content/stylesheets/application.scss
The only place I can see it have an impact is on small radios and the dark blue looks a bit odd.
Here is the Design System on the left and the guide on the right before the change:
After the change they'll look the same. Not sure what else this affects though! 🙈
=> Remove guide hover colour override

govuk_design_system_formbuilder.gemspec, guide/content/form-elements/checkboxes.slim, guide/content/form-elements/radios.slim, guide/content/form-elements/select.slim, guide/layouts/partials/belongs-to-warning.slim
Add warning on Rails relationship presence checks
This problem has occurred since Rails added default validation to Rails' belongs_to relationships in version 6.
Usually when creating forms we set relationships using the foreign key column, i.e. `department_id`, not the `department` relationship
attribute itself .
This mismatch causes errors on the object to be reported in the error summary but they won't link properly to the input because it's mapped to a different field.
Solving the problem itself is complex so this is a tentative first step and adds warnings to the guide.
It's _really hard_ to concisely say what's going on, any feedback on wording welcome.
Refs #411
- Add RedCarpet markdown rendering to the guide
- Add warning on Rails relationship presence checks
(possible misuse of …
=> Add warnings on `belongs_to` presence validation field mismatch

lib/govuk_design_system_formbuilder.rb, lib/govuk_design_system_formbuilder/elements/date.rb, spec/govuk_design_system_formbuilder/builder/configuration/date_segment_configuration_spec.rb
This change should make it easier for people to add custom date validation by giving them control of the identifiers used by Rails' multiparameter fields.
This was suggested in #489 and in [the linked PR] the `i` (which tells Rails to cast to an Integer) is removed, allowing the custom validation to take place before Rails tries casting the values to a `Date`.
=> Make the default date segments configurable

lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/date.rb, spec/govuk_design_system_formbuilder/builder/date_spec.rb
Following on from #493 this allows the date segments to be overridden on a field-by-field basis instead of just at the app level.
=> Make date segments overridable

lib/govuk_design_system_formbuilder/elements/legend.rb, spec/support/shared/shared_legend_examples.rb
This updates the legend element to allow the size attribute to be `nil`, and when `nil` a size class won't be specified for the element. This is required to support the case where a field has a legend element but shouldn't have a size class.
There's an example of this kind of component in the GOV.UK Design System:
https://design-system.service.gov.uk/components/date-input/#if-youre-asking-more-than-one-question-on-the-page
It's currently not possible to re-create this example using purely the form builder classes as the size is enforced as one of `s`, `m`, `l` or `xl`.
=> Allow legend size to be nil

guide/content/introduction/labels-captions-hints-and-legends.slim, guide/content/stylesheets/application.scss, guide/lib/examples/labels_captions_hints_and_legends.rb, guide/lib/helpers/person.rb, lib/govuk_design_system_formbuilder/builder.rb, spec/govuk_design_system_formbuilder/builder/label_spec.rb
This PR exposes `GOVUKDesignSystemFormBuilder::Elements::Label` directly via `#govuk_label`. It's intended to allow authors to place the label somewhere other than immediately above the input.
Its usage isn't covered by the design system so comes with the risk that the error message will still be rendered next to the input which will likely break layouts when used in confined spaces (i.e., table cells)
The regular label arguments will still work so authors can customise the label's:
* size
* wrapping tag
* caption
* visibility
=> Standalone labels

.github/workflows/publish.yml, .github/workflows/tests.yml, README.md, guide/content/introduction/supported-versions.slim
Ruby 3.1 support is dropped because Rails 8 depends on Ruby 3.2 and above.
=> Upgrade to latest versions of Ruby and Rails

guide/lib/setup/example_data.rb
`view_component` v3.20.0 has removed `require "ostruct"` from their codebase:
https://github.com/ViewComponent/view_component/releases/tag/v3.20.0
As such, users that want to use `OpenStruct` have to add the `require` call to their codebases.
Instead, we can use `Struct`, which works similarly and doesn't have to be required.
=> Use `Struct` in examples

guide/content/form-elements/file-upload.slim, guide/lib/examples/file.rb, lib/govuk_design_system_formbuilder/builder.rb, lib/govuk_design_system_formbuilder/elements/file.rb, spec/govuk_design_system_formbuilder/builder/file_spec.rb
The latest version of govuk-frontend ([v5.9.0](https://github.com/alphagov/govuk-frontend/releases/tag/v5.9.0)) includes a new JS-enhanced version of the file upload component.
The nunjucks macro has a `javascript` flag for enabling this:
```njk
{{ govukFileUpload({
id: "file-upload",
name: "photo",
label: {
text: "Upload your photo"
},
javascript: true
}) }}
```
which inserts a div with a class and data attribute around the input element:
```html
<div class="govuk-form-group">
<label class="govuk-label" for="file-upload-1">
Upload a file
</label>
<div
class="govuk-drop-zone"
data-module="govuk-file-upload">
<input class="govuk-file-upload" id="file-upload-1" name="fileUpload1" type="file">
</div>
</div>
```
This PR adds a new javascript flag to the govuk_file_field to accomplish the same …
=> Add flag for JS enhanced file upload
